### ISSUE TITLE
Include Schuhmacher's work on reporting

### ISSUE THREAD

**Issue by lama0206** [jplag/JPlag#1]

**Comment by tsaglam** [comment]
Closed, as it is no longer relevant.

**Comment by sebinside** [comment]
Rest in Peace, Issue #1!

**Comment by lama0206** [comment]
Seriously, guys, that this project is still alive makes me sentimental. And that it's strong and going forward makes me kind of proud having had - at least a tiny - impact on the publication here 💪 

PS @tsaglam : I'm still convinced that SE101 TAs (for internal use "SWT1-Tutoren") are the best of the best.

**Comment by tsaglam** [comment]
We are happy to carry on the torch with JPlag here.

> I'm still convinced that SE101 TAs (for internal use "SWT1-Tutoren") are the best of the best.

I cannot disagree with that! 😄

**Comment by lama0206** [comment]
> I cannot disagree with  that!

Who could, who could ever?
