### ISSUE TITLE
Add minimal update notifications

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#1001]
To raise awareness for newer JPlag versions, the program should check its version against the current release using the public GitHub API. If a newer version is available, this should be shown in a small notification (that does **not** annoy the user). Alternatively, this could also be shown in a small info text in the report viewer.

**Comment by tsaglam** [comment]
Ideally, this would be shown in the report viewer.

**Comment by Kr0nox** [comment]
@sebinside This should be completed with #1240 if im not mistaken?

**Comment by tsaglam** [comment]
Closed by #1240.
