### ISSUE TITLE
Scalameta dependency cannot be bumped

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#1008]
Currently, the Scala dependency version update PR #986 does not build. This has been the case for a few minor versions.
This means a release of Scala changed the compiler in a way that affects the token extraction. As a consequence, our tests fail.

- [x] Investigate how the actual token sequence differs from the expected one
- [x] Check where this change comes from
- [x] Decide, if our token extraction rules need an update
- [x] Either fix tests or update rules

**Comment by sebinside** [comment]
Fixed in #986
