### ISSUE TITLE
Language-specific option for token string normalization

### ISSUE THREAD

**Issue by brodmo** [jplag/JPlag#1028]
There is currently an unused `normalizeSubmissions` method in `SubmissionSet`. Instead, the `SubmissionSet` constructor should check whether token string normalization is enabled through the `JPlagOptions` object it has and perform the normalization if it is enabled. The token string normalization option would need to be language-specific as it is not supported for all languages.

**Comment by tsaglam** [comment]
Relates to #920.

**Comment by tsaglam** [comment]
Closed, as normalization can be controlled via `--normalize`.
