### ISSUE TITLE
Add Maven Central support

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#108]
After each release, the new version shall be automatically published on maven central.

https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven

**Comment by sebinside** [comment]
Required prior steps:
- [ ] Change package naming from `jplag` to `de.jplag`
- [ ] Find out, who actually owns jplag.de, lol

**Comment by tsaglam** [comment]
We are still working on getting access to JPlag.de (trouble with the hoster), which is the reason why the Maven Central release is currently delayed.
