### ISSUE TITLE
Rework Actions

### ISSUE THREAD

**Issue by dfuchss** [jplag/JPlag#1147]
Actions should only be triggered, if the underlying source code has changed.

E.g., https://github.com/jplag/JPlag/blob/1e58c739472d8eebe54572f17574c75a86271a3e/.github/workflows/sonarcloud-report-viewer.yml#L8

**Comment by dfuchss** [comment]
@jplag/hiwi if some of you finds the time :)

**Comment by sebinside** [comment]
In this line of work, the sonarcloud check fails on dependapot pull requests (that should probably not checked), e.g., here: https://github.com/jplag/JPlag/pull/1154

**Comment by dfuchss** [comment]
Yes, I forgot to disable the sonarlint checks for dependabot.
