### ISSUE TITLE
Workflows dont run on changes in PR

### ISSUE THREAD

**Issue by Kr0nox** [jplag/JPlag#1166]
In #1145 many Workflows did not run again after pushing new changes.
These include:
- Sonarcloud report viewer
- e2e tests report viewer
- report viewer build workflow
- report viewer unit test

These are all the actions that have a trigger set to pull_request only and not push

**Comment by dfuchss** [comment]
@tsaglam the workflows will be triggered if merged to main.

**Comment by dfuchss** [comment]
@Kr0nox the PR starts the workflow at https://github.com/jplag/JPlag/pull/1145#issuecomment-1612651758

**Comment by dfuchss** [comment]
-> https://www.githubstatus.com/

**Comment by Kr0nox** [comment]
> GitHub currently has problems with actions. Therefore, I close the issue for now.

Is this issue still persisting? [https://www.githubstatus.com/](https://www.githubstatus.com/) says they should be operating as normal but again only the actions triggered by the `push` were executed and non triggered by the `pull_request`

**Comment by dfuchss** [comment]
Workflows will not run on pull_request activity if the pull request has a merge conflict. The merge conflict must be resolved first.
