### ISSUE TITLE
Remove non-english comments and documentation

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#118]
Maybe because this is a 25 years old project, there are comments and documentation available only in German that shall be translated.

**Comment by tsaglam** [comment]
Left to do (edit if more are found):

- [ ] [CPP.jj](https://github.com/jplag/JPlag/blob/master/jplag.frontend.cpp/src/main/javacc/CPP.jj) (comments)
- [ ] [Report.java](https://github.com/jplag/JPlag/blob/master/jplag/src/main/java/de/jplag/reporting/Report.java) (hardcoded HTML)

**Comment by tsaglam** [comment]
I consider this issue as resolved. If somebody still finds some non-English line of code, feel free to make another issue.
