### ISSUE TITLE
Viewing log output

### ISSUE THREAD

**Issue by mbrdl** [jplag/JPlag#1191]
Is there any way to view the complete logs? It would be especially helpful if they could be written to a file.

**Comment by tsaglam** [comment]
Currently, there is no built-in way, and it is not a planned feature. If you want to do so locally, just modify the logger to do so

**Comment by mbrdl** [comment]
What are the logs for then, even?

**Comment by dfuchss** [comment]
The logs are important if you use JPlag as library.

**Comment by mbrdl** [comment]
For any other lost souls: Using the flags
`-Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG -Dorg.slf4j.simpleLogger.logFile=all.log`
seems to work. I would really like a config file, and I couldn't figure out how to make one, or how the logging works in general, for that matter, but I guess it's not my concern. Could be worth looking into if anyone feels like it
