### ISSUE TITLE
Writing result zip takes too long

### ISSUE THREAD

**Issue by brodmo** [jplag/JPlag#1212]
With larger submission sizes (>500) zipping and writing the output makes up the bulk of the runtime and takes overall way too long. The main reason for this is probably that a file is written for every comparison pair. Writing the result should be made faster or made skippable, ideally both.

**Comment by tsaglam** [comment]
With the current implementation, it takes ~5 seconds on my M1 MacBook with the board game dataset (434 submissions, with a mean size of 1529 LOC). Overall runtime ~35 seconds (14 seconds parsing, 11 seconds comparison). Thus, I would consider it closed for now.
