### ISSUE TITLE
CLI Run

### ISSUE THREAD

**Issue by m-jabari** [jplag/jplag#129]
Hey Guys,
Would you please, get me a minimum executable CLI command?

My CLI info:
ubuntu 20
*.c source code folders: **~/Desktop/fnFiles**
lang: ***.c**
root jplag git clone folder: **~/Desktop/jplag**
jar generated folder: **~/Desktop/jplag/jplag/target**
report folder: **~/Desktop/report**
my sample, which I'm calling it from **~/Desktop/jplag/jplag/target*:

> _java -jar jplag-3.0.0-SNAPSHOT-jar-with-dependencies.jar_ -l c_cpp -bc /home/ubuntu/Desktop/jplag/jplag/target  -v details -d Debug -S /home/ubuntu/Desktop/jplag/jplag/target -t 1 -s 0.7 -r ~/Desktop/report

Thank you

**Comment by tsaglam** [comment]
It seems like you are building your own jar from our current pre-release build. I would recomment you to use the latest [stable release](https://github.com/jplag/jplag/releases). For the legacy version of JPlag (2.12.1) call the jar without CLI arguments to see what arguments can be used. For example:

> java -jar jplag-2.12.1-SNAPSHOT-jar-with-dependencies.jar your/sorcecode/folder -l c_cpp -s -r your/report/folder

Note that you seem to use the `target` directory as base code directory, which does not make a lot of sense. The base code is a common framework that is used in all submissions. For example, a stub in which students fill out an empty method body.
