### ISSUE TITLE
Problems with running  jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by tsferreira** [jplag/jplag#14]
I downloaded this version of JPlag and tried to run it with the command:
     java -jar jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar -l c -s  mydir
and I got: 
      "Error: Illegal value: Language instantiation failed: Unknown language "c" ". 
The same happened with "-l cpp". It seems to work only for the several versions of Java.

On the other hand, option "-p ?" produces: 
      "Error: No language found...".

I also tried to recompile JPlag by running: "mvn package" which produced a file: jplag-2.11.8-SNAPSHOT.jar. When I tried to execute it using the same command above, I got:

Exception in thread "main" java.lang.NoClassDefFoundError: jplag/Language
	at jplag.JPlag.main(JPlag.java:12)
Caused by: java.lang.ClassNotFoundException: jplag.Language
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 1 more

All tests were executed under Ubuntu Linux, with Maven as follows:
 
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T14:41:47-02:00)
Maven home: /home/tomasz/temp/apache-maven-3.3.9
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-77-generic", arch: "i386", family: "unix"

Any help will be appreciated. I am not very knowledgeable about Java and even less about Maven ;-(.

**Comment by lama0206** [comment]
The name of the c/c++ front end is c/c++, you have to specify it that way (unfortunately, JPlag does not recognize `c` or `cpp`). The command should be `java -jar jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar -l c/c++ -s mydir`

Regarding your second question: The jplag jar built by `mvn package` does not contain any language front ends. If you want to build your own stand-alone (single-file) version of jplag, run `mvn assembly:assembly` inside the jplag directory.

**Comment by tsferreira** [comment]
What about:

> ... option "-p ?" produces: 
> "Error: No language found...".

**Comment by lama0206** [comment]
If you specify -p you have to specify -l somelanguage as well. Somehow the default language is not chosen, when -p is present.

**Comment by tsferreira** [comment]
I think I did not understand. I tried:

    java -jar jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar -l c/c++ -p ?

and I got:

Language accepted: C/C++ Scanner [basic markup]
Command line: -l c/c++ -p ? 
initialize ok
Error: "" is not a directory!

Adding a directory just changes the error message. Isn't "-p ?" supposed to list available languages?

**Comment by lama0206** [comment]
No. Starting JPLag without arguments prints the options (and the available languages). `-l` selects a language and `-p` tells JPlag what file name suffixes should be treated as files written in that langugae. So if you saved all c++ files as *.cplusplus, you would specify `-l c/c++ -p cplusplus`. `-p ?` tells JPlag to use the default file name suffixes for the chosen language.

**Comment by tsferreira** [comment]
Got it -- thanks!

**Comment by lama0206** [comment]
No problem :)

**Comment by tsferreira** [comment]
I have another question. I have the following directory structure for student's programs (example):

<pre>
task_01/
    section_A/
         student_001/
               file_1.c
               file_2.c
               file.h
         student_002
               file_1.c
               file_2.c
               file.h
          .....   more students
    section_B/
         student_101/
               file_1.c
               file_2.c
               file.h
          .....   more students
     ..... more sections
</pre>

I would like to run JPlag on all programs in all sections, i.e., I would like to specify something equivalent to:

<pre>
    java -jar jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar -l c/c++  task_01/*/*     
</pre>

Is there any parameter combination that does it?

**Comment by lama0206** [comment]
I guess the simplest way is to remove the `section_*` directories and move all `student_*` directories to `task_01`. Then add `-s` to the command line arguments if there are sub-directories below `student_*` and run JPlag on `task_01`

**Comment by tsferreira** [comment]
Yes, of course, but I can't change my directory structure which is part of a program submission system. I guess I will have to copy all submissions into another directory. 

Thanks anyway!

**Comment by brun0xff** [comment]
What is error?
no main manifest attribute, in python-3-0.0.1-SNAPSHOT-jar-with-dependencies.jar

**Comment by SfarwaB1994** [comment]
I want to run jpal for assembly codes, what should i use after -l ???????
