### ISSUE TITLE
Host a demo of the report viewer

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#1428]
Ideally, we would have a hosted version of the JPlag report viewer showing the results of a JPlag run for a publically available dataset, e.g. progpedia. Thus, users can see and test our features without downloading executing JPlag themselves.

**Comment by Kr0nox** [comment]
#1000 has something related to this
> The CD deployed version should have sample files ready to go (added in the deployment pipeline)

**Comment by Kr0nox** [comment]
Should be hosted in a new Repository called `Demo`.

**Comment by tsaglam** [comment]
Closed by #1448. See https://jplag.github.io/Demo/.
