### ISSUE TITLE
Version 21 of Java

### ISSUE THREAD

**Issue by euberdeveloper** [jplag/JPlag#1534]
In the releases the last release is for Java 17 and not 21 as in the docs

**Comment by tsaglam** [comment]
We are preparing the main branch for the upcoming v5.0.0 release, so the docs are currently in a pre-release state. If you have any issues or questions, please let us know. We are there to help!

**Comment by euberdeveloper** [comment]
Ok thanks!

So I think I can build from source code for now. I also have other questions about the program but I think that a separate issue is better
