### ISSUE TITLE
Unexpected parser error, all submissions are excluded

### ISSUE THREAD

**Issue by Victue** [jplag/jplag#158]
I set` '-x' 'E:/jplag_test/exclude/Dengyangyang_Hello.java`, but 
```
Initialized language Javac 1.9+ based AST plugin
JPlag initialized
Excluded files:

  public class Dengyangyang_Hello
  */
  public static void main(String[] args)
  System.out.println("Hello World");
  * @param args
  // TODO Auto-generated method stub
  {
  }
  /**
Exclude submission: Dengyangyang_Game.java
Exclude submission: Dengyangyang_Hello.java
Exclude submission: DongYouWei_Game.java
Exclude submission: dingxiaomin_Game.java

0 submissions parsed successfully!
0 parser errors!

Total time for parsing: 0 sec
Time per parsed submission: n/a msec

Error: Not enough valid submissions! (found 0 valid submissions)
```
In **[JPlag.java](https://github.com/jplag/jplag/blob/master/jplag/src/main/java/jplag/JPlag.java)**
```
    public boolean isFileExcluded(File file) {
        if (excludedFileNames == null) {
            return false;
        }
        return excludedFileNames.stream().anyMatch(excludedName -> file.getName().endsWith(excludedName));
    }
```
```
    private Vector<Submission> mapFileNamesInRootDirToSubmissions(String[] fileNames, File rootDir)
            throws ExitException {
        Vector<Submission> submissions = new Vector<>();

        for (String fileName : fileNames) {
            File submissionFile = new File(rootDir, fileName);
            
            if (isFileExcluded(submissionFile)) {
                System.out.println("Exclude submission: " + submissionFile.getName());
                continue;
            }
```
I found `excludedFileNames` will keep the previous value, and `isFileExcluded(submissionFile)` will keep `ture`.
In fact, I didn't set these files to be excluded. Is there something wrong with my setting?
Please help me, thank you.

**Comment by tsaglam** [comment]
Which version of JPlag do you use? v2.12.2 or earlier? Or the current pre-release build for v3.0.0 (meaning the current state of the master branch)?

**Comment by Victue** [comment]
thanks tsaglam for your helping reply. I use pre-release build for v3.0.0, I'm trying to improve on that.

**Comment by tsaglam** [comment]
Thanks for the information, we will look into this issue.

**Comment by tsaglam** [comment]
May it be that you are using the `-x` argument incorrectly?
`-x` should be followed by a path to a file that contains the files to ignore, meaning each file name a new line.
Can you create such a text file (e.g. blacklist.txt) containing `Dengyangyang_Hello.java`, then set `-x` to `path/to/blacklist.txt` and see if it works?

**Comment by Victue** [comment]
Thank you, I did use it by mistake hahaha. I confused `-x` and `-bc`，I'm very sorry for wasting your time

**Comment by tsaglam** [comment]
No worries, glad I could help!
