### ISSUE TITLE
[bug] File structure discrepancy 

### ISSUE THREAD

**Issue by eslamHegazy** [jplag/JPlag#1610]
I am using Jplag 5 (jar release) through the api and the online report-viewer https://jplag.github.io/JPlag/

A simple example for the problem
Root directory A
A/sub1.java
A/sub2.java

Old submissions directory B
B/o1.java
B/o2.java

When viewing the report on the online report-viewer and trying to open any comparison, I face a failure. After inspecting the problem for a few hours: I found out that
Inside the zip file, my submissions are in paths:
files/A_sub1.java/sub1.java
files/A_sub2.java/sub2.java
files/B_o1.java/o1.java
files/B_o2.java/o2.java
While the comparisons json files and submissionFileIndex.json assumes they are in paths:
files/A_sub1.java/A_sub1.java
files/A_sub2.java/A_sub2.java
files/B_o1.java/B_o1.java
files/B_o2.java/B_o2.java

**Comment by tsaglam** [comment]
Fixed by #1645. It will be part of the next minor release.
