### ISSUE TITLE
Report Viewer can not display multiple matches in the same line

### ISSUE THREAD

**Issue by Kr0nox** [jplag/JPlag#1617]
Attached an example data set. I included each submission once in the original way and formatted.
In the formatted you can see, that there are two matches, and in the original the match list also shows that, but it can not be seen in the code view, since the second match draws over it.

[dataset.zip](https://github.com/jplag/JPlag/files/14431396/sameLine.zip)

**Comment by tsaglam** [comment]
Closed by #1695.
