### ISSUE TITLE
Report viewer refuses reports with unknown language

### ISSUE THREAD

**Issue by Alberth289346** [jplag/JPlag#1641]
I maintain a private version of JPlag with our own CIF language in it.

Today I found a bug report by a teacher that the report viewer of 5.0.0 does not accept our result file.

- Reported report viewer version. Note that it states that it supports JPlag 4.2 and higher.
![PastedGraphic-1](https://github.com/jplag/JPlag/assets/3254232/a5a5779d-e979-4769-9482-da5c729dadca)

- Report viewer feedback when feeding a file with results from the CIF language
![PastedGraphic-2](https://github.com/jplag/JPlag/assets/3254232/37ee87f2-178c-4944-985f-fd1b1b45460b)

- git log of the build that I created:
![Screenshot from 2024-03-06 13-31-08](https://github.com/jplag/JPlag/assets/3254232/a3190802-7a24-45b8-a8cd-cc449f340734)

As you can see, I used JPlag 4.3.0 for the build, which seems newer than 4.2.0 to me.

Now, what to do?

@davbeek  ping!

**Comment by Kr0nox** [comment]
For the report viewer to be able to extract the language from the `overview.json` file, please add the language to the coresponding enum here: https://github.com/jplag/JPlag/blob/main/report-viewer/src/model/Language.ts

If you want to have custom code highlighting for your language you can add it to the `getHighlightLanguage` method here: https://github.com/jplag/JPlag/blob/main/report-viewer/src/utils/CodeHighlighter.ts

**Comment by Alberth289346** [comment]
I can write a PR for that, but how does that work from there?

We're running a 4.3 Jplag program, and use your report viewer, as far as I know.

- Will you make the adapted reportviewer available for us?
- Is it a good idea to add random additional languages there for which you don't have a jplag front-end?
- Wouldn't it be simpler to simply accept the results with a default value there like "unknown language", or (in our case) "CIF language" (since it seems to know the word CIF) ?

**Comment by Alberth289346** [comment]
Note that this is a regression, it used to work before. I am not sure why it now suddenly needs a known language.

**Comment by tsaglam** [comment]
Hi @Alberth289346, thanks for the feedback. We will discuss this issue and try to find a suitable solution.

**Comment by tsaglam** [comment]
@Alberth289346, with #1648, this should be resolved. With the next minor release, it will be part of the hosted report viewer. As a workaround, using the develop version works right now: https://jplag.github.io/JPlag-Dev/
However, this version is obviously less stable than the main one.

**Comment by Alberth289346** [comment]
Thanks for the quick response!

Hopefully it is in time for the teacher to check for plagiarism now.
