### ISSUE TITLE
Document volume testing

### ISSUE THREAD

**Issue by sebinside** [jplag/jplag#166]
For validation of newer Jplag versions, volume testing can be used to find problems in the underlying analysis.

Starting from v3.0.0, this shall be done for every major release and the results shall be anonymized and documented.

This also requires new testing and report generation capabilities.

**Comment by tsaglam** [comment]
We could build an in-depth test case that compares a `JPlagResult` object in detail (as in every single match), but is by default disabled and or has some dummy input. This could then be used locally with unpublishable large-scale test files. If this test case should take some comparison data as input (for example like the CSV files in the generated report) and compare it with the test files.
