### ISSUE TITLE
Java 9+ Parser Token swap parameters upon super constructor call (potential bug)

### ISSUE THREAD

**Issue by tsaglam** [jplag/jplag#172]
The[ Java 9+ Token](https://github.com/jplag/jplag/blob/master/jplag.frontend.java-1.9/src/main/java/jplag/java19/JavaToken.java) swap parameters upon super constructor call.
```java
public JavaToken(int type, String file, int col, int line, int length) {
    super(type, file, col, line, length); // super constructor from jplag.Token takes line THEN column...
}
```

**Comment by DrMichaelPetter** [comment]
This was probably just a typo, so refactoring the parameter names should be fine

**Comment by tsaglam** [comment]
Thanks for the input, I will look into it!
