### ISSUE TITLE
Latest viewer not rendering correctly for some Java code

### ISSUE THREAD

**Issue by sh1670** [jplag/JPlag#1786]
Hi,

When I use the latest viewer some of the code does not render (Java).

* Here is a java snippet hosted on the latest hosted pm jplag's github.io: [latest](https://drive.google.com/file/d/1eiYgr5CAYaFF159on72Y7OuIW2f3aoYz/view?usp=sharing)
* Here is the same code rendered by version 4.3 running on localhost (thanks for clear instructions for doing this): [4.3](https://drive.google.com/file/d/1Id_disOZcJkFoKiwS5LaRt_qNNXid3fh/view?usp=sharing)

Thanks!

**Comment by Kr0nox** [comment]
Could you provide us with the original code, so we know whether tabs or spaces were used in case that is causing the issue

**Comment by sh1670** [comment]
[Here](https://drive.google.com/file/d/18xvEzC0lmLvpOoCdhSMMGRdc2z67BbCz/view?usp=sharing) is some code which reproduces the issue.

Can you let me know when you have downloaded and I will stop sharing it as it contains a tiny bit of an assignment solution?

Thanks again,

Sion

**Comment by Kr0nox** [comment]
@sh1670 I have downloaded it

**Comment by sh1670** [comment]
That was fast! Thanks.
