### ISSUE TITLE
Clicking at the "arrows" in the generated html doesn't work at all.

### ISSUE THREAD

**Issue by Alberth289346** [jplag/JPlag#186]
In the generated html, there are black "arrow-like" symbols near matched areas to (probably) show the linked area in the left and right frame.

In my Firefox (version 92.0) brwoser, clicking at them doesn't do anything.
Web developer tool says:
![Screenshot from 2021-09-17 07-41-31](https://user-images.githubusercontent.com/3254232/133732487-2576f914-2026-4b66-b3be-7a7316b21549.png)

What happens is that the clicked link activates the `ZweiFrames` function which tries to set the `location.href` to a new URL (as far as I understand it). FireFox refuses to do this, since the pages are not in the same domain.

https://bytes.com/topic/javascript/answers/92223-permission-denied-get-property-location-href links the error to "same origin policy"

https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy explains about it

Since it's a security measure, I would expect it's a matter of time before other browsers will follow.

Unfortunately, as I have no clue how to program javascript in html, I don't know how to fix this.

**Comment by tsaglam** [comment]
We plan on completely rewriting the report system, which would solve this issue. However, this will take place after the v3.0.0 release (maybe in v3.1.0). Thanks for making us aware!

**Comment by YoungFrog** [comment]
Using legacy 2.12 version ; for me it helped to view the files through a local webserver, e.g. using `php -S localhost:5042` from the directory containing index.html

Hope it helps.

(I couldn't make it work with v3.0.0 -- it's not using frames anymore)

**Comment by rkopper** [comment]
On 3.0.0, there are no html frames, and the zweiframes function has been removed. However, the anchor links still call the zweiframes function, and it's not possible to navigate the page with the arrows.

**Comment by tsaglam** [comment]
v4.0.0 will contain the new report viewer. The current prototype is on the master branch but still has some work to do.
Thus we will not fix any issues regarding the legacy report viewer.

**Comment by tsaglam** [comment]
Closed, as the old report viewer is already removed from the repo.
