### ISSUE TITLE
 [WARN] Token - Creating a token with column index 0 while index is 1-based

### ISSUE THREAD

**Issue by ruanye** [jplag/JPlag#1903]
"I ran into two problems with 'java -jar jplag.jar -l text -n 10000./test -r result'
1. Data is incomplete, less than one group of data comparison, the use of '-n-1' is also
2. There is a warning '[WARN] Token - Creating a token with column index 0 while index is 1-based'
 I'm using the latest version

**Comment by tsaglam** [comment]
First, beware of the text language module. In contrast to the programming language modules, the way it works is very outdated, nowadays there are better methods to detect plagiarism in natural language. The text language is very much legacy.

- Regarding 1: I am not sure if I fully understand, make sure that there is a space between the number and the directory: `-n 10000 ./test`
- Regarding 2: Do you have a code snippet to reproduce this?

**Comment by ruanye** [comment]
抱歉我重新测试了下数据是正确的，我就是用最简单的 demo 写的普通的测试，也加了空格，但是仍然我不明白这个警告的意思。当使用 
 text 文本的时候的警告  [WARN] Token - Creating a token with column index 0 while index is 1-based

**Comment by tsaglam** [comment]
This is related to an internal bug in the JPlag code. So, it's not an issue on your end. If you could provide a text snippet though, we can take a look at it.

**Comment by ruanye** [comment]
[duplicate_01.zip](https://github.com/user-attachments/files/16607254/duplicate_01.zip) 
it is then demo  
use  
```bash
java -jar jplag.jar -l text ./duplicate_01  -r result
```

**Comment by tsaglam** [comment]
Your provided example contains JavaScript code in text files. Using the text language module will not yield good results for code. You should use `-l javascript` and convert the .txt files into javascript files. We will look into the index issue, though.
