### ISSUE TITLE
Support for Objective-C

### ISSUE THREAD

**Issue by Norwa9** [jplag/JPlag#1954]
Is there a plan to support Objective-C?

**Comment by tsaglam** [comment]
Currently, there are no plans for it. However, we could add it to the language wishlist (#685).
If you want to contribute an objective c language module yourself (e.g., based on the https://github.com/antlr/grammars-v4/ grammar), please refer to the wiki and existing ANTLR based language modules (e.g. C# https://github.com/jplag/JPlag/tree/main/languages/csharp).

**Comment by tsaglam** [comment]
Is now part of #685.
