### ISSUE TITLE
Java 1.8 support

### ISSUE THREAD

**Issue by ninewise** [jplag/jplag#20]
Thanks for this great tool. Any chance support for java 1.8 will be added? The program seems to work reasonable fine on java 1.8 code with the `-l java17` flag, but I (and probably my students as well) would like to be sure the reports are valid.

**Comment by lama0206** [comment]
Dear Felix

Some day, jplag will fully support Java 8. Until then, you can "safely" use the Java 7 setting. As long as the sources can be parsed, the results are valid. If one of the sources contains a Java 8 feature (such as lambda expressions), parsing will fail an the file will be excluded from the comparison though.

Regards Mathias 

On May 24, 2016 5:08:17 PM GMT+02:00, Felix Van der Jeugt <notifications@github.com> wrote:
>Thanks for this great tool. Any chance support for java 1.8 will be
>added? The program seems to work reasonable fine on java 1.8 code with
>the `-l java17` flag, but I (and probably my students as well) would
>like to be sure the reports are valid.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jplag/jplag/issues/20

-- 
Mathias Landhäußer 
Eisenhutstr. 14
76703 Kraichtal

T: +49 7251 3810012
M: +49 175 1970705

**Comment by NoctuaNivalis** [comment]
Thank you for your explanation, I will patiently await that day.

**Comment by thrau** [comment]
Hi! I also want to express my thanks for this great tool. We use it extensively at TU Wien for several bachelor's and master's courses (courses with up to 300 participants) and it does a great job!

However, with the increase use of Java 8 features, the hit rate noticeably decreases, which makes it increasingly difficult for me to weed out plagiarism. So I wanted to ask if there are any concrete plans towards Java 8 support? If not, is it possible to outline the key changes that have to be made for someone unfamiliar with the codebase to get some starting points to make the necessary contributions?

**Comment by waynetee** [comment]
Hi @thrau!
What do you mean by the hit rate noticeably decreases?
JPlag should still be able to perform matching on the parts of the files that could be parsed.

I believe adding Java8 support will be quite difficult to do correctly. You would need to (somewhat) understand the Java grammar. I made an attempt [here](https://github.com/waynetee/jplag/tree/java8). You would need to edit jplag/jplag.frontend.java-1.8/src/main/java/jplag/java18/JplagJava8Listener.java to work with the java 8 grammar and emit the right tokens to get everything to work. Hope this helps.

**Comment by isko04** [comment]
Dear JPlag-Team,

I agree with the previous comments and I also think, that JPlag is a great tool. I am currently evaluating 
software for testing programming exercises, which also enclose a lot of Java8 code. So Java8 is a must.
Excuse me, I ask it again. What do you think, when will Java8 support for JPlag be available? Hope soon! 

I've done some short tests with release v2.11.9-SNAPSHOT, and found that it also works with Java8 sources. For example, for the lines of code 42 and 43 

```
42: myList.forEach((String element) -> System.out.println(element));
43: myList.forEach(element -> System.out.println(element));
```

the parser gives the following output, but no exception:
```

line 42:23 no viable alternative at input '(String element'
line 42:23 extraneous input 'element' expecting {'+=', '%=', '!=', '^=', '&&', '=', '^', '|=', '(', '-=', ',', '/=', '++', '<', '+', '*=', '/', '&=', '||', 'instanceof', '?', '&', '*', '.', '[', '==', '--', '|', '>', '%', ')', '-'}
line 42:33 no viable alternative at input '>'
line 42:62 extraneous input ')' expecting {'+=', '%=', '!=', '^=', '&&', '=', '^', '|=', '(', '-=', '/=', '++', '<', '+', '*=', '/', '&=', '||', ';', 'instanceof', '?', '&', '*', '.', '[', '==', '--', '|', '>', '%', '-'}
line 43:24 no viable alternative at input '>'
```

JPlag generates these tokens:

```
42 6 34 APPLY   
42 6 34 APPLY   
42 6 34 APPLY   
43 6 34 APPLY   
43 6 34 APPLY
```

where the first number is the line number, the second number the length, the third number the token type (J_APPLY from JavaTokenConstants) and the String at the end the textual representation of the type. It looks like the lambda expressions are ignored. Is this the way it works?

Lama0206 wrote 

> As long as the sources can be parsed, the results are valid. If one of the sources contains a Java 8 feature (such as lambda expressions), 
> parsing will fail an the file will be excluded from the comparison though.


Which Java8 feature will cause, that a whole file will be excluded form the comparison? Since in our case really many sourcefiles contain Java8 features, this would not be an option. Are the results still reliable?

For some playing around, I copied the before mentioned Repo for Java8 support. Unfortunately, I can't compile it in Eclipse, because some generated classes from antlr are missing. Is this, because some things still have to be done or should it be compilable? Could you maybe give one short example of what has to be done?

Thanks a lot!!!

**Comment by lama0206** [comment]
Hi there - I have no news regarding proper Java 1.8 support, sorry.

When you import the project in Eclipse, make sure to use the maven import, not the java project import. Then you can run maven with the goal `generate-sources` (right click on the module's project > run as > maven build... > insert `generate-sources` as "Goal" and then klick "Run"). Hope this helps.

**Comment by waynetee** [comment]
Hi @isko04 
I contribute to this repository but I am not part of the official JPlag team.

I'll try to answer your questions as best as I can

> When will Java8 support for JPlag be available?

I don't think there are people intending to implement "proper" support for Java8.

> It looks like the lambda expressions are ignored. Is this the way it works?

JPlag works by converting code into tokens, then performing matching on those tokens. You can say that JPlag works by abstraction.

Each Apply token represents a method call (more or less), as you can see, the apply tokens are being generated and they reflect the code given. The fact that the code uses lambdas is "abstracted away" but the tokens are still reflective of the code and can still be used for matching. 

> Which Java8 feature will cause, that a whole file will be excluded form the comparison?

I don't think that happens often if at all, if it does you should be able to see from the report as well as the commandline output that there are parse errors

> Are the results still reliable?

I believe so but I cannot guarantee this. I suggest you use JPlag as a tool to highlight suspicious cases and manually review each case.

> Could you maybe give one short example of what has to be done?

Did you use maven to build it? Maven should generate the antlr classes, but you may have to edit other files to make it work fully.

Hope this helps.

**Comment by isko04** [comment]
Hi, thanks for your quick response!

> > Did you use maven to build it? Maven should generate the antlr classes, but you may have to edit other files to make it work fully.

I used Maven - the same way than I did with the master-branch (as Lama0206 described, import as Maven project, generate-sources,...). Which other files do you mean?

> I don't think there are people intending to implement "proper" support for Java8.

That's a pity. Would have been a nice thing.

**Comment by waynetee** [comment]
I don't my code is compilable at its current state unfortunately. Its a half done thing I uploaded in case someone wants to carry on with the work using what I have completed. That person will need to be quite familiar with how JPlag works.

**Comment by isko04** [comment]
Ok, I understand. Thank you waynetee!

**Comment by weigelt** [comment]
The latest version of jplag (v2.12.0-SNAPSHOT) supports any Java version up to 11 (thanks to @DrMichaelPetter ).
Happy testing!

**Comment by thrau** [comment]
that is excellent, thank you @DrMichaelPetter and @weigelt for merging it.
i'll re-run last semester's submissions with the current snapshot and will report anything noteworthy. thanks again!
