### ISSUE TITLE
Merge additional frontends from (semi-) active forks

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#202]
We could merge some existing frontends to offer support for more languages. Candidates are the [Scala frontend](https://github.com/CodeGra-de/jplag/tree/master/jplag.frontend.scala), the [R frontend](https://github.com/CodeGra-de/jplag/tree/master/jplag.frontend.R), and the [Jupyter Notebook frontend](https://github.com/CodeGra-de/jplag/tree/master/jplag.frontend.ipython/src/main/java/jplag/ipython) from @CodeGra-de. The frontends would probably require a bit of cleanup and some minor changes need to be made to adapt them to recent changes of the frontend utils.

**Comment by tsaglam** [comment]
#56 also offers an R frontend, however, it currently cannot be merged due to conflicts.

**Comment by tsaglam** [comment]
There are many ANTLR grammars available, however, their license might vary and they are not available on mvn central.
Nevertheless, we could easily add more supported languages.

My personal wishlist:
- [ ] golang
- [ ] rust
- [ ] kotlin

**Comment by libre-man** [comment]
What we (CodeGrade) did in our fork is that we made it possible to use external processes to parse the languages. The major advantage is that you can use existing parsers from the language itself, this makes creating (and updating) parsers way easier. We are still in the process of optimising that, but if you want we can send a PR when we have finalised that.

**Comment by tsaglam** [comment]
Sounds interesting, I might have a look at it if I find some time. Do you have a link for me as a reference point?

**Comment by tsaglam** [comment]
Closed, as the viable language modules were adopted and merged in #570 and #455.
