### ISSUE TITLE
Process stuck

### ISSUE THREAD

**Issue by Rosyrain** [jplag/JPlag#2032]
When I compare different versions of a database written in golang, the process gets stuck and cannot proceed.
At first I used mac to do it, but later I switched to windows and this problem still exists
![image](https://github.com/user-attachments/assets/279c1eb9-e95d-4881-9cd1-b781f3265746)

**Comment by tsaglam** [comment]
@Rosyrain, can you provide more information on your input scenario? It could be that the input causes ANTLR to freeze.

**Comment by tsaglam** [comment]
Closed, as we cannot reproduce it.
