### ISSUE TITLE
Don't assume white background in class diagram.

### ISSUE THREAD

**Issue by Alberth289346** [jplag/JPlag#205]
Silly issue, but here goes.

I use Github dark mode, and the class diagram in the README looks as follows at my screen:

![Screenshot from 2021-10-25 10-00-24](https://user-images.githubusercontent.com/3254232/138657735-0e5e804a-ce51-4a5f-837e-3c5e23ffb48c.png)

The reason is that the image was created with transparent background under the assumption it would be shown with a light background.

The proper fix is to explain to the image generator to use solarized colours (designed to look useful at both light and dark backgrounds). The much simpler path is to generate a opaque image with a light background.

**Comment by tsaglam** [comment]
<p align="center">
	<img alt="UMLClassDiagram.png" src="https://raw.githubusercontent.com/jplag/jplag/master/UMLClassDiagram.png" width="800">
</p>
