### ISSUE TITLE
Can't import anything from jplagWsClient.jplagClient.* ?

### ISSUE THREAD

**Issue by Goldensunboy** [jplag/jplag#22]
I am trying to set up jplag in Eclipse, and am not able to do so because many files depend on imports from jplagWsClient.jplagClient.* for example:

> import jplagWsClient.jplagClient.JPlagException;
import jplagWsClient.jplagClient.JPlagService_Impl;
import jplagWsClient.jplagClient.JPlagTyp_Stub;
import jplagWsClient.jplagClient.LanguageInfo;
import jplagWsClient.jplagClient.Option;
import jplagWsClient.jplagClient.ServerInfo;
import jplagWsClient.jplagClient.Status;
import jplagWsClient.jplagClient.Submission;
import jplagWsClient.jplagClient.UserInfo;

However, I can't find any classes with those names or any packages named jplagWsClient.jplagClient in the sources provided here on github. Am I doing something wrong?

**Comment by lama0206** [comment]
Hi

You have to run mvn generate:sources to generate classes for the 
webservice (both, server and client - I think). If you don't want to 
build your own web service, you can ignore these modules...

Regards
Mathias

On 2016-05-31 20:54, Andrew Wilder wrote:
> I am trying to set up jplag in Eclipse, and am not able to do so because
> many files depend on imports from jplagWsClient.jplagClient.* for example:
>
>     import jplagWsClient.jplagClient.JPlagException;
>     import jplagWsClient.jplagClient.JPlagService_Impl;
>     import jplagWsClient.jplagClient.JPlagTyp_Stub;
>     import jplagWsClient.jplagClient.LanguageInfo;
>     import jplagWsClient.jplagClient.Option;
>     import jplagWsClient.jplagClient.ServerInfo;
>     import jplagWsClient.jplagClient.Status;
>     import jplagWsClient.jplagClient.Submission;
>     import jplagWsClient.jplagClient.UserInfo;
>
> However, I can't find any classes with those names or any packages named
> jplagWsClient.jplagClient in the sources provided here on github. Am I
> doing something wrong?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jplag/jplag/issues/22>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABKdE_OzZawtaAawzhjp4nhy40W58rAdks5qHIPfgaJpZM4Iq2AB>.
>

-- 
Mathias Landhäußer
Eisenhutstraße 14
76703 Kraichtal

T: +49 7251 3810012
M: +49 175 1970705

**Comment by Goldensunboy** [comment]
Thank you, that fixed the problem. I think I was confused because it didn't generate the sources by running mvn generate-sources in the root folder, but did when I ran it in the webService folder. My fault.

I guess that's intentional so you don't have to build the webService if you don't want, but in my opinion it probably should because so many other files in almost every other part of jplag depend on imports from webService, and the webService seems to be so highly integrated into other parts of jplag.
