### ISSUE TITLE
Update cli help and github wiki to better clarify -t (sensitivity of  the comparison)

### ISSUE THREAD

**Issue by csidirop** [jplag/JPlag#223]
At this moment nether the -h nor the github wiki have much information about the sensitivity of  the comparison. Both say `  -t T   Tune the sensitivity of  the comparison. A smaller <n> increases the sensitivity`.

Looking into the code it seams that the -t parameter defines JPlagOptions.minimumTokenMatch. I believe (or hope) its name is self-explanatory. It gets for every Language its own default value if non is set. For Java its 9, for C++ and python its 12 and for C# its 8. 

From my understanding the lower the value the less tokens are needed for a match (more sensitive). It seams that 0 is the lowest value (negative values will be treated as 0?).

With this information one can try find better results, but without its hard to guess some useful values.

**Comment by tsaglam** [comment]
Note that the smallest possible min token match should be 1, setting it to 0 should not be possible: https://github.com/jplag/JPlag/blob/5549b7bb2fe947806b3a0e9f7af1d29706b82a48/jplag/src/main/java/de/jplag/options/JPlagOptions.java#L201-L207
