### ISSUE TITLE
Big sensitivity value leads to NullPointerException in comparison if at least 1 submission is no longer valid

### ISSUE THREAD

**Issue by csidirop** [jplag/JPlag#225]
When setting a too big sensitivity (`-t`) value there is a chance, that submissions with little code becoming not valid.
But that leads later to a NullPointerException when the comparison starts. 
Here my anonymized example with 4 submissions:
```
java -jar .\jplag-3.0.0-SNAPSHOT-jar-with-dependencies.jar -x .\exclude-P8.txt -n -1 -m 70 -t 13  -v long -r result-P8sub -l java9 .\SUB2\ -bc VORLAGE
Initialized language Javac 1.9+ based AST plugin
Basecode directory ".\SUB2\\VORLAGE" will be used
JPlag initialized
Excluded files:
  IOTools.java
  TestChiffre.java
  Messobjekt.java
  Messung.java
  ZweistelligerOperator.java
  ImageTools.java
  StringUtils.java
  TestMessung.java
  Empfaenger.java
  Sender.java
------ Parsing submission: sub1
Submission contains fewer tokens than minimum match length allows!
ERROR -> Submission removed
------ Parsing submission: sub2
OK
------ Parsing submission: sub3
------ Parsing submission: sub4
OK

3 submissions parsed successfully!
0 parser errors!
1 submission is not valid because it contains fewer tokens
than minimum match length allows.



Total time for parsing: 0 sec
Time per parsed submission: 54 msec

----- Parsing basecode submission: VORLAGE

Basecode submission parsed!


Time for parsing Basecode: 0 sec
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "de.jplag.TokenList.size()" because the return value of "de.jplag.Submission.getTokenList()" is null
        at de.jplag.GreedyStringTiling.swapAndCompare(GreedyStringTiling.java:97)
        at de.jplag.GreedyStringTiling.compareWithBaseCode(GreedyStringTiling.java:92)
        at de.jplag.strategy.AbstractComparisonStrategy.compareSubmissionsToBaseCode(AbstractComparisonStrategy.java:29)
        at de.jplag.strategy.NormalComparisonStrategy.compareSubmissions(NormalComparisonStrategy.java:22)
        at de.jplag.JPlag.run(JPlag.java:85)
        at de.jplag.CLI.main(CLI.java:57)
```
I suppose that because the submission was removed after parsing, the comparison passes a null object and at one point it does not correctly check if the objects being compared are null.
With `-t 12` the submission is valid and the comparison runs as always.
Here is the example if needed: [testSub2.zip](https://github.com/jplag/JPlag/files/7561388/testSub2.zip)

**Comment by tsaglam** [comment]
Thanks for the detailed bug report, we will look into it!

**Comment by tsaglam** [comment]
It seems that invalid submissions are not really deleted. Instead, the token list is just set to null:
https://github.com/jplag/JPlag/blob/7f18cb8f912ab403ff4ec7c4fe92fdf7f6a59108/jplag/src/main/java/de/jplag/JPlag.java#L362-L367
The core algorithm then crashes upon comparison as it rightly expects a token list to be there.

**Comment by csidirop** [comment]
Okay, I believe there are two ways: deleting or just skipping that submission. 
But both could cause errors elsewhere when suddenly there are less submissions and the size of the ArrayList is not readout dynamically. Or there is a submission which was prior skipped. 
But that should only be an issue when the list is used elsewhere again.

These were just my initial thoughts, you have the greater overview of the project

**Comment by tsaglam** [comment]
I opted for the proper removal, as it seems to lead to no further issues. However, if you find any issues, lust let me know!

**Comment by csidirop** [comment]
Looks like it's working! Thanks
