### ISSUE TITLE
Deduplicate and encapsulate time calculation

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#227]
The time calculation for the comparison duration in the `JPlag` class is duplicated in several spots and generally scattered throughout the class. It should be deduplicated and encapsulated in a dedicated method or class.

**Comment by UtkarshDeoli** [comment]
ok i can do this

**Comment by tsaglam** [comment]
Great! Let me know if you have any questions!

**Comment by tsaglam** [comment]
Note that PR #230 seems to fix this issue.

**Comment by UtkarshDeoli** [comment]
ok

**Comment by tsaglam** [comment]
@UtkarshDeoli feel free to contribute to [other issues](https://github.com/jplag/JPlag/issues?q=is%3Aissue+is%3Aclosed+label%3A%22good+first+issue%22) if you want to! Help is always appreciated!
