### ISSUE TITLE
Can I run JPLAG as local? without connecting to the internet?

### ISSUE THREAD

**Issue by saeedsryhini** [jplag/jplag#23]
I'm sorry but I couldn't quite understand this point when it's mentioned on the "Web Service" section.
So, can I run JPLAG as local? or this project is used to actually send tokens to JPLAG server over the internet, and then get the results back?

**Comment by lama0206** [comment]
There is a web service server and a GUI contained in the repository. You can build and host a JPlag server if you want/need to. I recommend running JPlag locally from the command line. You'll get the same results.
