### ISSUE TITLE
Missing information in JPlagResult and JPlagOptions objects

### ISSUE THREAD

**Issue by cholakov11** [jplag/JPlag#248]
The following information is missing in the JPlagResult/JPlagOptions object but it could be useful for the report:

## JPlagResult
- [x] **List of failed submissions.** Through the list size their amount can also be acquired.

## JPlagOption
- [x] **List of names of excluded files.** The object contains name of excluded file but it needs to be read in order to obtain the names. However the file is already being read one time when starting the JPlag comparison. I would suggest this read to be stored so we can avoid duplicated coded and multiple same file accesses at different places in the code.

**Comment by GabrielL** [comment]
For the second part, I have started this https://github.com/GabrielL/JPlag/pull/1 but since in my actual PR #272 there is a lot of refactoring around these parts, it is for the moment based on it, (hence the local pull request on my personal fork instead of here)

**Comment by tsaglam** [comment]
I just took your commits from GabrielL#1 and put them on top of #273 (author-preserving) in order to have everything in the same PR for this issue!

**Comment by tsaglam** [comment]
@cholakov11 Failed submissions can now be accessed via the result object, which contains the submission set, while the excluded file names are currently available through the options, which is temporary and might change due to #274. I hope this helps with the new report generation!
