### ISSUE TITLE
Extend the spotless configuration

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#292]
Spotless could be extended to support [ANTLR4](https://github.com/diffplug/spotless/tree/main/plugin-maven#antlr4) and other formatting rules. More info can be found in the [spotless docs](https://github.com/diffplug/spotless/tree/main/plugin-mave).

**Comment by tsaglam** [comment]
Also, support for typescript and other web dev languages.

**Comment by tsaglam** [comment]
Formatting ANTLR is probably not the best idea, but at least something like the generic indent step could be used.
For the Scala language module, however, we could enable spotless. Maybe also for other language modules?

**Comment by Kr0nox** [comment]
Since we wont be formatting ANTLR and with #1029 and #1111 there is automatic style checking and applying, is this issue still relevant? @tsaglam

**Comment by tsaglam** [comment]
@Kr0nox no, then we can close this for now.
