### ISSUE TITLE
Basecode directory doesn't exist, but name appears to have been mangled

### ISSUE THREAD

**Issue by chipbuster** [jplag/JPlag#293]
Hey there!

I'm trying to run JPlag with a basecode name. Here's the command I'm running:

```
java -jar jplag-3.0.0-jar-with-dependencies.jar -bc /home/chipbuster/Codes/teaching/moss-alternatives/testfiles/base_code/utcsh/  -d -l cpp -v long -p .c -n 50 /home/chipbuster
/Codes/teaching/moss-alternatives/testfiles/codedumps/utcsh/
```

And here's the output I'm getting:

```
Initialized language C/C++ Scanner [basic markup]
Error: Basecode directory "/home/chipbuster/Codes/teaching/moss-alternatives/testfiles/codedumps/utcsh//homechipbusterCodesteachingmoss-alternativestestfilesbase_codeutcsh" doesn't exist!
```

It looks like the basecode directory name is getting mangled (all slashes stripped out) and then appended to itself to make the final directory name.

Usually my trick at this point would be to grep into the code base for the error message, but to my confusion, this error message doesn't actually seem to appear in the codebase.

Please let me know if I've screwed up the command, or if you'd like any additional information! I tested this running OpenJDK/JRE17 and Oracle JDK/JRE17, so I don't think it's a bug with my Java runtime, though I could be wrong.

**Comment by tsaglam** [comment]
Which version of JPlag do you use? A release? Or did you package your own from the master branch?

**Comment by chipbuster** [comment]
This was the 3.0.0 jar with dependencies downloaded from the GH releases page (https://github.com/jplag/JPlag/releases/download/v3.0.0/jplag-3.0.0-jar-with-dependencies.jar)

**Comment by tsaglam** [comment]
Ah, I see. We are currently building the next release, where basecode is specified independently from the root folder via a path. In v3.0.0, the basecode should reside in the root folder and it is still specified via the name of the folder only.

Could you move your basecode (let's say the folder is named `basecodefoldername`) into the root folder (I guess it is utcsh)
and then try the following: 

```
java -jar jplag-3.0.0-jar-with-dependencies.jar -bc basecodefoldername -d -l cpp -v long -p .c -n 50 /home/chipbuster
/Codes/teaching/moss-alternatives/testfiles/codedumps/utcsh/
```

More info for the v3.0.0 interface is in the [wiki](https://github.com/jplag/JPlag/wiki/1.-How-to-Use-JPlag).

**Comment by chipbuster** [comment]
Well, I goofed that one, huh?

Thanks for the wiki link, I'm not entirely sure how I managed to miss it. Looks like a root directory with several submission directories is the structure I needed to make this work.

**Comment by tsaglam** [comment]
Not your fault, the problem is that the readme on this repo shows already the CLI parameters for the upcoming version. However, this is misleading for using the released jars. We should really add a version number to the readme! 👍
