### ISSUE TITLE
Add support for php

### ISSUE THREAD

**Issue by lama0206** [jplag/JPlag#3]

**Comment by tsaglam** [comment]
Closed, as the current frontend plans go in other directions. If somebody is interested to build such a frontend I can reopen this issue.

**Comment by olberger** [comment]
Uh... was the issue about adding PHP for managing web interface of the program, or to handle PHP source code plagiarism ? Just in case, PHP is present in #685

**Comment by olberger** [comment]
@tsaglam would it make sense to reopen this issue ?
