### ISSUE TITLE
Can't compile jplag

### ISSUE THREAD

**Issue by TurboKid** [jplag/jplag#30]
Hi,
I want to use Jplag for python files, and saw it exists at as a frontend.
I tried to compile it using maven but it's getting stuck.
Is there a new snapshot that python is already compiled into?

**Comment by waynetee** [comment]
here try this, you can also double click it or run it without java -jar for a gui version
[JPlag.zip](https://github.com/jplag/jplag/files/853250/JPlag.zip)

**Comment by TurboKid** [comment]
Great, Thank you!
