### ISSUE TITLE
Error: no main manifest attribute, in python-3-0.0.1-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by brun0xff** [jplag/jplag#31]
Error on parser python3

**Comment by waynetee** [comment]
Hi, whats does this refer to?
"python-3-0.0.1-SNAPSHOT-jar-with-dependencies"

**Comment by lama0206** [comment]
The language front ends are not meant to be run by themselves. They are modules used by jplag to parse files.

In addition: I believe @waynetee's comment to issue #6 solved this problem...
