### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by maximzubkov** [jplag/JPlag#315]
Hey! Thank you very much for your work on `JPlag`!
My name is Maksim, I am a master's student at EPFL, and I was experimenting with your tool and encountered the following problem:
`Failed to execute goal on project jplag: Could not resolve dependencies for project edu.kit.ipd.jplag:jplag:jar:2.12.1-SNAPSHOT: Failed to collect dependencies at edu.kit.ipd.jplag:frontend-utils:jar:0.0.3-SNAPSHOT: Failed to read artifact descriptor for edu.kit.ipd.jplag:frontend-utils:jar:0.0.3-SNAPSHOT: Could not transfer artifact edu.kit.ipd.jplag:frontend-utils:pom:0.0.3-SNAPSHOT from/to ipdNexus (http://bob.ipd.kit.edu/nexus/repository/maven-public-all): Transfer failed for http://bob.ipd.kit.edu/nexus/repository/maven-public-all/edu/kit/ipd/jplag/frontend-utils/0.0.3-SNAPSHOT/frontend-utils-0.0.3-SNAPSHOT.pom 503 Service Unavailable -> [Help 1]`

**Comment by dfuchss** [comment]
Hi @maximzubkov you may have to update to release 3.0.0 (that is deployed to maven central)

The old jars may be not available since (as far as I can see) the nexus at http://bob.ipd.kit.edu/nexus/ is not up.

**Comment by dfuchss** [comment]
Maybe you have to update all urls to https://bob.ipd.kit.edu/nexus/ there the nexus is still running :)

**Comment by maximzubkov** [comment]
Thanks a lot for your answers @tsaglam @dfuchss!
Legacy branch solved the problem, I will close the issue
