### ISSUE TITLE
Add support for c# 4.0 (or newer)

### ISSUE THREAD

**Issue by lama0206** [jplag/JPlag#4]

**Comment by iStehle** [comment]
Ich hab mal aus Gründen an einem c# 4 Support gearbeitet. Ich hab mich an dem Java7 Beispiel orientiert, leider schaffe ich es nicht mal die erste zeile Code zu lesen.
"line 1:0 no viable alternative at input 'ï»¿'"

Mir fehlt gerade die Idee an was das überhaupt liegen könnte. Mein Stand ist in meinem Fork zu finden

**Comment by lama0206** [comment]
Das ist eine Fehlermeldung von Antlr. Lade die Grammatik mal in die Antlr Workbench - die hat einen debug-Modus, der es erlaubt, Eingaben mit der Grammatik auszuwerten. Dort sollte besser sichtbar sein, was das Problem ist.

**Comment by fmcarvalho** [comment]
Is there any other support for C# with generics (at least)?

I tried to use the fork available at: https://github.com/iStehle/jplag/tree/c%23-support, but unfortunately I got the same error cited above: 

> line 1:0 no viable alternative at input 'ï»¿'

**Comment by tsaglam** [comment]
Closed by #400 and #413. We now support at least up to C# 6. Any feedback is welcome.
