### ISSUE TITLE
i only substitute variable name but got a 0% Matches

### ISSUE THREAD

**Issue by Long7777** [jplag/JPlag#430]
I have three java codes,and i just substitute the variable name but i got a result that says there are  0% Matches
and also i wonder what's the "template" folder userd for?

**Comment by tsaglam** [comment]
What version of JPlag did you use? What CLI arguments did you use? How short or long are these files? matching sections need to be longer than the min token match argument.

**Comment by tsaglam** [comment]
Closed, not enough information. No way to reproduce.
