### ISSUE TITLE
c/c++ files are not parsed..

### ISSUE THREAD

**Issue by reddyvasavi** [jplag/jplag#46]
![screenshot from 2017-12-01 14-34-35](https://user-images.githubusercontent.com/19586192/33475673-3ebb53fc-d6a5-11e7-8098-0b56c30481a4.png)

**Comment by k-amin07** [comment]
I have the same error. were you able to resolve this?

**Comment by polcak** [comment]
I specify extensions to check, e.g. "java -jar jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar -l c/c++ -r results-feedreader -s -p c,cc,cpp,cxx,h,hpp directory". It would be nice if jplag detects the extensions automatically.
