### ISSUE TITLE
Using Issue

### ISSUE THREAD

**Issue by sirshahriar** [jplag/jplag#53]
![annotation](https://user-images.githubusercontent.com/39922982/40933978-1016477c-6855-11e8-81f4-bef02881ad8d.png)
![capture](https://user-images.githubusercontent.com/39922982/40934561-fdafd772-6856-11e8-8c75-5c331d55c9ee.PNG)

Please tell me whats the problem

**Comment by lama0206** [comment]
You've used the option `-1 java17` - you should use `-l java17`

The -l stands for "**l**anguage" not for "one" ;)
