### ISSUE TITLE
Support Swift

### ISSUE THREAD

**Issue by krusche** [jplag/JPlag#533]
We teach Swift in our university courses and would like to be able to run plagiarism checks on it. Therefore, it would be nice if Swift could be supported.

**Comment by tsaglam** [comment]
We considered adding a Swift frontend before (as part of the discussions around #345), so this is something we might implement soon. It is good to know that a Swift frontend may find use. A possible implementation will probably be based on an [existing antlr v4 grammar](https://github.com/antlr/grammars-v4/tree/master/swift/swift5).

**Comment by krusche** [comment]
Great, let us know how to support you, we could e.g. advertise this contribution as part of a bachelor thesis

**Comment by tsaglam** [comment]
Closed, as we now collect language requests in #685.
