### ISSUE TITLE
Single parse errors ignores the entire submission

### ISSUE THREAD

**Issue by libre-man** [jplag/jplag#54]
If a single file in the submission has a parse error the entire file is ignored. This makes the detection quite vulnerable as students simply need to hand in one invalid file.

**Comment by wllhf** [comment]
Why is this closed? I think this is quite a severe problem.

**Comment by tsaglam** [comment]
See [this comment](https://github.com/jplag/JPlag/issues/80#issuecomment-878364971).
Process-wise, it is probably best anyways to expect your students to submit code that is valid/compiles.

**Comment by wllhf** [comment]
Yes, it is and I understand the problem. But this way a student can avoid to be detected by just adding a file that cannot be parsed. Furthermore it would be nice to generate a list of submissions that were not included as looking through the console output if you have hundreds of submission of which dozens aren't parseable is quite tedious.

**Comment by tsaglam** [comment]
The CLI output will list all invalid files **after** parsing and **before** comparison:

```
JPlag initialized
ERROR: nothing to parse for submission "Empty
5 submissions parsed successfully!
3 parser errors!
0 too short submissions!

The following errors occured:
[A - broken] Demo3\A - broken\Structure.java:7: error: ';' expected
        int hash_length = -1
                            ^
[A - broken] Demo3\A - broken\Token.java:44: error: illegal start of expression
        public static int numberOfTokens() {
        ^
[D - broken] Demo3\D - broken\TokenConstants.java:4: error: = expected
  final static int FILE_END  0;
```

This will help you to see all invalid submissions at one. Then you can fix them and run them again if you want to accept invalid submissions from students. However, you can always solve that problem by requiring students to submit functioning code.
