### ISSUE TITLE
Base code exclusion does not appear to work

### ISSUE THREAD

**Issue by malexmave** [jplag/jplag#55]
I'm running JPlag on a batch of submissions from our students. We gave them a base framework of Java code with some empty functions to fill in. I'm providing our base source code with -bc, but it still detects the base engine code as plagiarism between the files. The command line I used was:

    java -jar jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar -S [some subpath] -s -bc ../template -l java17 -p java submissions/

"submissions" contained around 200 folders with a uniform format. The template was outside of the "submissions" hierarchy, because otherwise, it was plagiarism-checked, even though it was given as a base code directory.

I am currently unable to provide an example dataset here, as the grading is not yet complete and I can't publicly release the student's code. If you want me to send you one privately, please let me know who to send it to. The same is true if you need any additional information.

```bash
$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
$ uname -a
Linux Max-Work 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by galgalesh** [comment]
I have the same issue. Let me know if I can provide any info to help debug this.

**Comment by floe** [comment]
Yes, same issue here, using 2.11.9. I will try the latest master branch and see if it makes a difference.

**Comment by svetozarm** [comment]
Same issue here with 2.11.9.

**Comment by LoraIpsum** [comment]
Hi! Had the same issue. The solution was to place basecode folder (called template here) **inside** the directory with submisssions. Would be good if it was listed in readme file.

**Comment by floe** [comment]
@LoraIpsum finally got around to testing this; however, it didn't seem to make a difference in my case. The basecode folder just got treated like any other submission, and the identical parts across all submissions still got flagged...

**Comment by floe** [comment]
Of course, 10 seconds after posting this, I figured it out. 

Assume the following folder structure:
```
submissions
    + exercise1
        + basecode
        + student1
        + student2
    + exercise2
        + basecode
        + student1
        + student2
    ...
```
This commandline doesn't work (basecode is just treated like another submission):
`cd submissions; java -jar ~/soft/jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar -l java17 -r results/ -bc basecode/ -s exercise1/`

However, the following _does_ work (note the different working directory):
`cd submissions/exercise1; java -jar ~/soft/jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar -l java17 -r results -bc basecode -s .`

I agree, this needs to be in the README.

**Comment by argoc** [comment]
I am curious to know if this would work:

`cd submissions; java -jar ~/soft/jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar -l java17 -r results/ -bc exercise1/basecode -s exercise1`

**Comment by floe** [comment]
Just tried that, doesn't work: `Error: Basecode directory "exercise1/exercise1/basecode/" doesn't exist!`.

**Comment by weigelt** [comment]
> This commandline doesn't work (basecode is just treated like another submission):
> `cd submissions; java -jar ~/soft/jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar -l java17 -r results/ -bc basecode/ -s exercise1/`

The command works without the final slash (after the basecode folder). This (surely) is a bug. We will see to that asap.

**Comment by weigelt** [comment]
> I am curious to know if this would work:
> 
> `cd submissions; java -jar ~/soft/jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar -l java17 -r results/ -bc exercise1/basecode -s exercise1`

This command won't work as the base code directory is seen as a relative path (from the root dir). That's why you'll see the message from @floe's comment

**Comment by weigelt** [comment]
We've updated the README. However, it already mentioned the assumed base code location before. Hopefully it's clearer now. I've also mentioned the bug (s.o.).
