### ISSUE TITLE
ArgParse4J might be unmaintained

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#550]
[ArgParse4J](https://github.com/argparse4j/argparse4j) is currently unmaintained (see this [PR](https://github.com/argparse4j/argparse4j/pull/139)). We should keep an eye on that and might consider using an alternative in the future. For now, this issue serves to document this problem, and no action is required.

**Comment by sebinside** [comment]
Probably related to the incoming CLI rework (do we already have an issue for that?) and also to #572.

**Comment by dfuchss** [comment]
I think the rework of the CLI includes a discussion about the actual parameters that are needed as well.

We could use something like:
[https://github.com/Kotlin/kotlinx-cli](kotlinx-cli) is incubator but makes it very easy to create CLIs (and maintained by jetbrains).

Example also [here](https://github.com/LiSSA-Approach/LiSSA-Core/blob/main/cli/src/main/kotlin/edu/kit/kastel/lissa/cli/CommandLineInterface.kt)

**Comment by tsaglam** [comment]
> do we already have an issue for that?

Now we have one: #591

**Comment by dfuchss** [comment]
@tsaglam may be closed

**Comment by tsaglam** [comment]
Closed by #1064.
