### ISSUE TITLE
Return normalized comparison similarity value (interval [0, 1])

### ISSUE THREAD

**Issue by JanWittler** [jplag/JPlag#567]
Currently, `JPlagComparison` returns a value between 0 and 100 for the similarity. This is not really intuitive and probably makes computation on these values more complex.

Instead, I would propose to return a value between 0 and 1. This will require adjustments in the results visualization and maybe in the results serialisation.

**Comment by tsaglam** [comment]
Regarding intuition, the methods of the comparison class are clearly documented, so it should be really obvious that it is a percentage. I am not entirely convinced, that switching to normalized value will bring many benefits. It just moves the complexity into the report viewer and creates a divide between the programmatic usage of JPlag and the usage via CLI and the report viewer.

**Comment by tsaglam** [comment]
Internal discussion results in the decision to normalize similarity in the result object but not in the report viewer. In the viewer, we depict %.
