### ISSUE TITLE
Unable to build, ipdNexus repository 503 error

### ISSUE THREAD

**Issue by GaryBennett** [jplag/jplag#57]
Hi,

I am having problems building JPlag.

During the build all downloads from the ipdNexus repository fail.

Any help would be greatly appreciated.

Kind regards,
Gary

`$ mvn clean generate-sources assembly:assembly`
`[INFO] Scanning for projects...`
`[INFO] `
`[INFO] ----------------------< edu.kit.ipd.jplag:jplag >-----------------------`
`[INFO] Building jplag 2.11.9-SNAPSHOT`
`[INFO] --------------------------------[ jar ]---------------------------------`
`[INFO] `
`[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jplag ---`
`[INFO] Deleting /usr/src/mymaven/jplag/target`
`[INFO] `
`[INFO] --- build-helper-maven-plugin:1.7:add-source (add-antlr-source) @ jplag ---`
`[INFO] Source directory: /usr/src/mymaven/jplag/target/generated-sources/antlr added.`
`[INFO] Source directory: /usr/src/mymaven/jplag/target/generated-sources/javacc added.`
`[INFO] `
`[INFO] --- javacc-maven-plugin:2.6:javacc (javacc) @ jplag ---`
`Java Compiler Compiler Version 5.0 (Parser Generator)`
`(type "javacc" with no arguments for help)`
`Reading from file /usr/src/mymaven/jplag/src/main/javacc/filter.jj . . .`
`File "TokenMgrError.java" does not exist.  Will create one.`
`File "ParseException.java" does not exist.  Will create one.`
`File "Token.java" does not exist.  Will create one.`
`File "JavaCharStream.java" does not exist.  Will create one.`
`Parser generated successfully.`
`[INFO] Processed 1 grammar`
`[INFO] `
`[INFO] ----------------------< edu.kit.ipd.jplag:jplag >-----------------------`
`[INFO] Building jplag 2.11.9-SNAPSHOT`
`[INFO] --------------------------------[ jar ]---------------------------------`
`[INFO] `
`[INFO] >>> maven-assembly-plugin:2.4:assembly (default-cli) > package @ jplag >>>`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/frontend-utils/0.0.3-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:frontend-utils:0.0.3-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/frontend-utils/0.0.3-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:frontend-utils:0.0.3-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:frontend-utils:0.0.3-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/frontend-utils/0.0.3-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/frontend-utils/0.0.3-SNAPSHOT/frontend-utils-0.0.3-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.1exp/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:java-1.1exp:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.1exp/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:java-1.1exp:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:java-1.1exp:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.1exp/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.1exp/0.0.1-SNAPSHOT/java-1.1exp-0.0.1-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/utils/0.0.3-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:utils:0.0.3-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/utils/0.0.3-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:utils:0.0.3-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:utils:0.0.3-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/utils/0.0.3-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/utils/0.0.3-SNAPSHOT/utils-0.0.3-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/text/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:text:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/text/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:text:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:text:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/text/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/text/0.0.1-SNAPSHOT/text-0.0.1-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.5/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:java-1.5:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.5/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:java-1.5:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:java-1.5:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.5/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.5/0.0.1-SNAPSHOT/java-1.5-0.0.1-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.7/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:java-1.7:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.7/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:java-1.7:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:java-1.7:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.7/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/java-1.7/0.0.1-SNAPSHOT/java-1.7-0.0.1-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/python-3/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:python-3:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/python-3/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:python-3:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:python-3:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/python-3/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/python-3/0.0.1-SNAPSHOT/python-3-0.0.1-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/csharp-1.2/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:csharp-1.2:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/csharp-1.2/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:csharp-1.2:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:csharp-1.2:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/csharp-1.2/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/csharp-1.2/0.0.1-SNAPSHOT/csharp-1.2-0.0.1-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:cpp:0.0.2-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:cpp:0.0.2-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:cpp:0.0.2-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/cpp-0.0.2-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/scheme/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:scheme:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/scheme/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:scheme:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:scheme:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/scheme/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/scheme/0.0.1-SNAPSHOT/scheme-0.0.1-SNAPSHOT.pom`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/chars/0.0.1-SNAPSHOT/maven-metadata.xml`
`[WARNING] Could not transfer metadata edu.kit.ipd.jplag:chars:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/chars/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`[WARNING] Failure to transfer edu.kit.ipd.jplag:chars:0.0.1-SNAPSHOT/maven-metadata.xml from http://bob.ipd.kit.edu/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced. Original error: Could not transfer metadata edu.kit.ipd.jplag:chars:0.0.1-SNAPSHOT/maven-metadata.xml from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/chars/0.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Unavailable.`
`Downloading from ipdNexus: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/chars/0.0.1-SNAPSHOT/chars-0.0.1-SNAPSHOT.pom`
`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 3.716 s`
`[INFO] Finished at: 2018-10-16T00:04:17Z`
`[INFO] ------------------------------------------------------------------------`
`[ERROR] Failed to execute goal on project jplag: Could not resolve dependencies for project edu.kit.ipd.jplag:jplag:jar:2.11.9-SNAPSHOT: Failed to collect dependencies at edu.kit.ipd.jplag:frontend-utils:jar:0.0.3-SNAPSHOT: Failed to read artifact descriptor for edu.kit.ipd.jplag:frontend-utils:jar:0.0.3-SNAPSHOT: Could not transfer artifact edu.kit.ipd.jplag:frontend-utils:pom:0.0.3-SNAPSHOT from/to ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/): Failed to transfer file: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/frontend-utils/0.0.3-SNAPSHOT/frontend-utils-0.0.3-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1]`
`[ERROR] `
`[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.`
`[ERROR] Re-run Maven using the -X switch to enable full debug logging.`
`[ERROR] `
`[ERROR] For more information about the errors and possible solutions, please read the following articles:`
`[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by lama0206** [comment]
Dear Gary

It seems that IPD's Nexus server is not available at the moment. They should resolve this issue shortly. Until then, you should be able to run the mvn command like this:

```
$ mvn clean generate-sources install
$ mvn assembly:assembly
```

Best
Mathias

**Comment by GaryBennett** [comment]
Thank you.

Out of curiosity what is in the IDP's Nexus repository, does this mean until the server is up my builds will have missing features?

**Comment by lama0206** [comment]
Maven can use pre-built artifacts and it is configured to look for them in a repository that's being hosted by [KIT](https://ps.ipd.kit.edu). If this repository is not available, you get the error message that you've posted. Running mvn install builds all needed artifacts and stores them on your machine so that they are available during the assembly build.

So in short: No, there are no missing features. You'll end up with a "full version" of Jplag.
