### ISSUE TITLE
JPlag - option variants for the endToEnd tests

### ISSUE THREAD

**Issue by SuyDesignz** [jplag/JPlag#590]
To be able to extend the endToEnd tests further I would like to discuss which options are useful for the tests or which of these options should be included in the endToEnd tests. 
[](url)
Therefore, in advance here is the excerpt for the various calls of the options and their meaning from [How to Use JPlag](https://github.com/jplag/JPlag/wiki/1.-How-to-Use-JPlag):

```
Usage: JPlag [ options ] [<root-dir>]
 <root-dir>        The root-directory that contains all submissions

named arguments:
  -h, --help             show this help message and exit
  -l                     {java,python3,cpp,csharp,char,text,scheme} Select the language to parse the submissions (Standard: java)
  -bc BC                 Name of the subdirectory of the root directory which contains the base code (common framework used in all submissions)
  -v                     {quiet,long} Verbosity of the logging (Standard: quiet)
  -d                     Debug parser. Non-parsable files will be stored (Standard: false)
  -S S                   Look in directories <root-dir>/*/<dir> for programs
  -p P                   comma-separated list of all filename suffixes that are included
  -x X                   All files named in this file will be ignored in the comparison (line-separated list)
  -t T                   Tunes the comparison sensitivity by adjusting the minimum token required to be counted as a matching section. A smaller <n> increases the sensitivity but might lead to more false-positives
  -m M                   Match similarity threshold [0-100]: All matches above this threshold will be saved (Standard: 0.0)
  -n N                   The maximum number of comparisons that will be shown in the generated report, if set to -1 all comparisons will be shown (Standard: 30)
  -r R                   Name of the directory in which the comparison results will be stored (Standard: result)
  -c                     {normal,parallel} Comparison mode used to compare the programs (Standard: normal)
```
### Options Variants

I have made a pre-selection of options that seem useful for the EndTopEnd tests:
- (-c) for normal or parallel
- (-m) for similarity  threshold
- (-t) comparison sensitivity

The other options do not make sense for the current end to end tests in my opinion and would rather be verified by unit tests. 

### Addition:
While going through the code in the JPlagOptions.java classes I noticed that there are methods that are not used. These are mainly the set functions of the variables that are already set in the constructor of the class. 

``` java
    /**
     * Constructor with required attributes.
     */
    public JPlagOptions(List<String> submissionDirectories, List<String> oldSubmissionDirectories, LanguageOption languageOption) {
        this.submissionDirectories = submissionDirectories;
        this.oldSubmissionDirectories = oldSubmissionDirectories;
        this.languageOption = languageOption;
    }
```

for the variables passed here there are also setter methods but they have not been referenced in the project and therefore I wanted to ask if it is not possible to remove them. 

``` java 
//Line 282
    public void setOldSubmissionDirectories(List<String> oldSubmissionDirectories) {
        this.oldSubmissionDirectories = oldSubmissionDirectories;
    }
```

```  java
//line 286
    public void setSimilarityMetric(SimilarityMetric similarityMetric) {
        this.similarityMetric = similarityMetric;
    }
```

The exception is the setSubmissionDirectories() function which is used by tests and not actively by the API call:

``` java
//line 278
    public void setSubmissionDirectories(List<String> submissionDirectories) {
        this.submissionDirectories = submissionDirectories;
    }
```

**Comment by JanWittler** [comment]
If the code is unused, simply remove it and make a small PR for it 👍🏼 

#### Regarding your proposed options:
- (-t) comparison sensitivity +1 as different values will lead to different similarity values.
- (-c) The normal or parallel comparison should not change the results of the comparison and thus is not suitable here. Actually, as soon as #534 is merged, we can adapt the parallel comparison strategy to avoid locking problems and turn it on by default, removing this CLI argument. (And should certainly add unit tests assuring that identical results as in normal comparison are obtained.)
- (-m) The same is true for the similarity threshold. This value only filters out values **after** comparison has been performed, i.e. setting the value will not affect the similarity values.

From the other options you have quoted I am the same opinion as you that they are not interesting for end to end testing.

**Comment by tsaglam** [comment]
I agree with Jan. For now only -t is relevant, but keep it open for extension for future options.

Regarding unused methods:

- setOldSubmissionDirectories() could be removed, but we can also keep it to allow more flexible option construction
- setSimilarityMetric() cannot be removed, as this is the only way to set it
- setSubmissionDirectories could be removed but we can also keep it to allow more flexible option construction

Not that the options are an integral part of the public API, and CLI is only one way to use JPlag. Thus, unreferenced methods are not a problem per se.

**Comment by SuyDesignz** [comment]
Then I will include "comparison sensitivity (-t)" in the endToEnd tests for the version as well as the possibility to set options. Regarding the unused code, I would then do nothing because of the above reasons. 

Thanks for your time!

`- question closed -`
