### ISSUE TITLE
The java version used by JPlag3 is too high

### ISSUE THREAD

**Issue by mAndisan** [jplag/JPlag#592]
Hello,
     Java11 used by my idea project，can't reference JPlag3 (java14).
Is there any way?

**Comment by dfuchss** [comment]
JPlag is currently using Java SE 17 as it is the current LTS version of Java.

You could try to recompile JPlag for Java 11 (but I'm very sure that we are already using features from Java 17 on the current `master` branch; but maybe that will work for the v3.0.0 tag)

**Comment by tsaglam** [comment]
> but maybe that will work for the v3.0.0 tag

We moved to Java 14 with #159. Recompiling for Java 11 may work, but then the Java language module may have problems with parsing Java 14 code.
