### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by lama0206** [jplag/jplag#6]

**Comment by kidozh** [comment]
I was wondering how to use it in python,would you please give me some methods or tools?Thanks a lot!

**Comment by lama0206** [comment]
This ticket is about making JPlag check programs written in Python3, not about using JPlag with Python...

There is no python interface for accessing JPlag. [Py4J](https://www.py4j.org/) should be an option.

**Comment by kidozh** [comment]
BTW,I am wondering how to use it.I use maven to build it,but I do not know how to run it and to put it in the tomcat or other webservice.I am looking forward to your reply.
I would like to use Jplag to detect the code plagiarism in the ACM championship.By using your software,I would like to give a free access to ACM members.This is my website,acm.kidozh.com(It is designed for Chinese users,Gobalization may not work well).

**Comment by lama0206** [comment]
You can build the webservice (jplag/jplag.webService/) and put it in a tomcat. There are a readme and some installation notes in that directory (both slightly outdated though). The webservice war can be build with maven.

**Comment by kslack-uat** [comment]
Thank you for adding the python3 support. 
My one question is how do I use it? When I specify the language using the -l python3 it says Error: Illegal value: Language instantiation failed: Unknown language "python3"

**Comment by waynetee** [comment]
Hmm you seem to be doing it correctly, are you using the right version? You have to compile the code yourself, the binary on the release page is outdated

**Comment by waynetee** [comment]
here try this, you can also double click it or run it without java -jar for a gui version
[JPlag.zip](https://github.com/jplag/jplag/files/853250/JPlag.zip)

**Comment by kslack-uat** [comment]
Thank you so much for pointing out the age of the binary. I was able to recompile (making sure to build with dependencies) and everything worked great.

**Comment by brun0xff** [comment]
Hey, im trying use this tool for detecting plagiarism in source code python, but i get this error:
       Error: Not enough valid submissions! (only 0 are valid):
Can you help me?

**Comment by brun0xff** [comment]
I  run
java -jar jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar -l python3 -s ./mydir

**Comment by waynetee** [comment]
Hi, your usage seems to be correct.
Can you tell me what's inside mydir? Are they all valid .py files or folders containing valid .py files?

**Comment by lama0206** [comment]
Python3 support is included in [release v2.11.9-SNAPSHOT](https://github.com/jplag/jplag/releases/tag/v2.11.9-SNAPSHOT) so we should close this issue...

@brun0xff: Can you run Jplag on python3 source files?
