### ISSUE TITLE
C/C++ false negative with for loops vs while loops

### ISSUE THREAD

**Issue by andrewjbennett** [jplag/jplag#60]
I'm not sure whether this is an inherent limitation of the parser, or whether it's something that can be improved.

This is an anonymised example of some code that wasn't flagged as a match:

File 1:
```c
for (x = 0; x < 10; x++) {
    for (y = 0; y < 20; y++) {
        // removed: 3 lines of character-for-character identical code
        // which involved creating/updating local variables and calling functions
    }
}
```

File 2:
```c
while (x < 10) {
    y = 0;
    while (y < 20) {
        // removed: 3 lines of character-for-character identical code
        // which involved creating/updating local variables and calling functions
        y++;
    }
    x++;
}
```

In this specific instance, there were 15 lines of identical code before this snippet (which were flagged), then the code above, followed by 10 identical lines (which weren't flagged, due to being less than the threshold), followed by another nested while/for loop.

I can construct a larger example to illustrate if necessary.

**Comment by libre-man** [comment]
This is a limitation of the algorithm used by jplag as the two code snippets produce different token streams. A possible solution would be to normalize programs first (so always first transform `for` to `while` loops). Hacking this in the current architecture doesn't seem trivial to me (as you would need to be able to produce useful line information too), it simply converts files to token streams currently.

**Comment by weigelt** [comment]
@libre-man is right. This a limitation of the approach and cannot easily be implemented.
