### ISSUE TITLE
Naming issues with the end-to-end module

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#605]
There are a few naming issues with the end-to-end test suite:

- The module name uses came case, the others don't, we should change `jplag.endToEndTesting` to `jplag.end2end-testing` or `jplag.endtoend-testing`
- The package name is using capitalized words, which is not standard-conforming, we should change `de.jplag.end_to_end_testing` to `de.jplag.end2end` or `de.jplag.endtoend`

These renaming refactoring should be done in their own PR.

**Comment by SuyDesignz** [comment]
Thanks for creating the issues! as soon as the other PR is ready I'll get to work on renaming it
