### ISSUE TITLE
Re-evaluate `JPlagOptions#baseCodeSubmissionName` backwards compatibility

### ISSUE THREAD

**Issue by JanWittler** [jplag/JPlag#625]
The current implementation supports backwards compatibility of the `JPlagOptions#baseCodeSubmissionName` as documented here:
```Java
/**
 * Path name of the directory containing the base code.
 * <p>
 * For backwards compatibility it may also be a directory name inside the root directory. Condition for the latter is
 * <ul>
 * <li>Specified path does not exist.</li>
 * <li>Name has not have a separator character after trimming them from both ends (leaving at least a one-character
 * name).</li>
 * <li>A submission with the specified name exists in the root directory.</li>
 * </ul>
 * It's an error if a string has been provided but it is neither an existing path nor does it fulfill all the conditions
 * of the compatibility fallback listed above.
 * </p>
 */
```

However, as we are moving towards a new major release, we should re-evaluate whether this functionality should be preserved. If we want to preserve it, we should at least refactor it to resolving the base path before initialising the options, such that the options are always initialised with a path (and then rename the attribute to `baseCodeSubmissionPath`.

**Comment by tsaglam** [comment]
This backward compatibility should be preserved, as it was designed specifically for the v4.0.0 release. Users that move to the new version will use basecode as previously, so this fallback saves them annoyances but warns them about the changed way of using it. We can remove the fallback in a future major version (e.g. v5.0.0).

**Comment by tsaglam** [comment]
(removed from v4.0.0 release board)
