### ISSUE TITLE
Documentation Enhance the new Report Viewer

### ISSUE THREAD

**Issue by nestabentum** [jplag/JPlag#626]
Documentation for the practical course _Ingenieursmäßige Software-Entwicklung_.
Task: Enhance the new Report Viewer #357 

I intentionally left out detailed descriptions and diagrams of the architecture as it is neither very complex nor interesting. It can be grasped rather quickly. Also diagrams and architecture documentation often quickly diverge from the actual implementation as developers fail to update it or try to avoid it as it is no fun.

**Comment by nestabentum** [comment]
# 1. How to Use

# Reporting

After a JPlag run a zipped result report is automatically created.
The target location of the report can be specified with the `-r` flag.

If the `-r` is not specified, the location defaults `result.zip`. Specifying the `-r` flag with a path `/path/to/desiredFolder` results in the report being created as `/path/to/desiredFolder.zip`.

Unless, there is an error during the zipping process, the report will always be zipped. In case the zipping process fails, the report will be available as unzipped under the specified location.

# Running the Report Viewer

The JPlag Report Viewer is a Vue 3 + Typescript standalone application which can be used to display the JSON files generated by the JPlag reporting. The application requires Node.js and npm to be installed on the system.

Before the first run execute:

- `npm install` in the /report-viewer folder.
- To start the application, run the `npm run serve` command in the /report-viewer folder.

After the application has been started the user can providing files to display in the following ways:

- by dragging and dropping the zip file created by JPlag into the report viewer
- by placing contents of the zip file created by JPlag in the `/report-viewer/files` folder

**Comment by nestabentum** [comment]
# 2. Contributing to JPlag

# Reporting design

_ReportObjectFactory_ is the starting point and anchor for the reporting process. _CLI_ calls `ReportObjectFactory#createAndSaveReport(result: JPlagResult, path: String)`, providing the factory with the result of the JPlag run and the desired target path for the report.
`ReportObjectFactory#createAndSaveReport` then goes on and delegates the creation of all necessary files and folders and consequently zips the report.

## Report File Structure

```
result.zip
│   overview.json
│
└───submissions
│   └───submissionId1
│       │   submission1File1
│       │   submission1File2
│       │   ...
│   └───submissionId2
│       │   submission2File1
│       │   submission2File2
│       │   ...
│   └───submissionId...
│       │   ...
│   └───submissionIdN
│       │   submissionNFile1
│       │   submissionNFile2
│       │   ...
│   submission1-submission2.json
│   submission1-submission3.json
│   submission1-submission....json
│   submission1-submissionN.json
│   submission2-submission3.json
│   submission2-submission....json
│   submission2-submissionN.json
│   ...
```

The report zip contains

- overview.json

  - The `overview.json` encapsulates the main information from a JPlagResult such as base directory path, language, min- and max-metric, etc. The `overview.json` provides data to the _OverviewView_ that is first displayed after the report is dropped into the viewer. Corresponds to the Java record _OverviewReport_.

- submissions

  - This folder contains all files of all submissions JPlag was run with. For each submission the `submissions` folder contains a subfolder with the name of the corresponding submission id. A subfolder for a submission contains all files of said submission.
    These files are displayed in the _ComparisonView_

- comparison files

  - For each submission pair submission1 submission2 with ids submissionId1 and submissionId2, the report contains either submissionId1-submissionId2.json or submissionId2-submissionId1.json. This file contains information the comparison between the two submissions, such as the similarity and concrete matches. Corresponds to the Java record _ComparisonReport_.

## Submission ids

### Report Viewer
The `overview.json` contains a map that associates a submission id to its display name. Formerly, there was no distinction between id and display name. The distinction had to be introduced as the display name can contain slash characters and is therefore unfit for internal processing. 
For internal use use in the report viewer use only(!) the submission id. Whenever the name of a submission has to be displayed in the report viewer, the id has to be resolved to its display name first. The report viewer's vuex store provides a getter for this resolution.

### JPlag 
At the beginning of report generation a map and a function that associate a JPlag _Submission_ to a submission id is built. Whenever you reference a submission in a report viewer DTO use this map/function to resolve the submission to its id. 

# Specifying additional report formats

Currently, the report generation only support the JSON format. As the Interface _FileWriter_ and its implementation _ToDiskWriter_ are responsible for writing files to the disk and do so in the JSON format, only little changes to this structure are necessary to enable other formats.

# Adding and displaying new attributes from JPlagResult

The new design of JPlag reporting and viewing enables the easy addition of new attributes. Adding a new attribute follows the pattern:

In JPlag:

1. Introduce a new attribute to the Java DTO that represents the file you aim to change.
2. Define how the attribute is obtained from the JPlagResult. Do so either by introducing a new component that extracts the attribute from the _JPlagResult_ or by modifying an existing component. _ReportObjectFactory_ then calls this component and assigns the result to the attribute defined in 1.

In the Report Viewer:

3. Introduce the new attribute to the Typescript DTO.
4. Define how the attribute is extracted from the JSON file.
5. Display the attribute in the desired Vue component.

## Example

An example is provided in the following section which explains how new attributes can be introduced to the JPlagReport and then processed in the report viewer. In the following example we add the number of tokens per match to the JPlag report and view.

Task: Adding the number of tokens in a match, which has to be displayed in the MatchesTable in the ComparisonView.

1. Add `int tokens` to _Match.java_ (sub-model of _ComparisonReport.java_)
2. Modify the existing component _ComparisonReportWriter.java_ to additionally extract the number of tokens in a match from the _JPlagResult_
   and save it in the Match DTO
3. Add `tokens: number` to _Match.ts_
4. Edit _ComparisonFactory.ts_ to get the number of tokens from the JSON report file. [report-viewer]
5. Edit `MatchTable.vue` to display the tokens number in the `ComparisonView.vue`.

**Comment by nestabentum** [comment]
# 3. Changes to README.md

Change

```java
// Optional
File outputDir = new File("/path/to/output");
Report report = new Report(outputDir);

report.writeResult(result)
```

to

```java
// Optional
ReportObjectFactory reportObjectFactory = new ReportObjectFactory();
reportObjectFactory.createAndSaveReport(result, "/path/to/output");
```

**Comment by JanWittler** [comment]
Overall looks fine to me. I just have some minor remarks. But probably @tsaglam or @sebinside should have a final look at it.

- I would write all code references in `code` instead of in _italic_
- From my perspective the section for **Specifying additional report formats** is unnecessary. I don't see a use case where that will become relevant.
- For the changes to the readme, just make a mini PR containing that change (and maybe additional documentation that you think should be added to the classes you worked with)

> The overview.json contains a map that associates a submission id to its display name. Formerly, there was no distinction between id and display name. The distinction had to be introduced as the display name can contain slash characters and is therefore unfit for internal processing.

I don't see any need to refer to legacy behaviour here. Just state how it works now.

**Comment by sebinside** [comment]
I will have a look at it when I return to the office next week. But from a fast glimpse, I should have not big remarks.

**Comment by sebinside** [comment]
So, in general, everything looks fine (except the comments already made by Jan). Additionally, I have only little remarks:
- `ReportObjectFactory#createAndSaveReport` why the `#` for separating class and method?
- `For internal use use` (duplicated word)
- When explaining `-r`, the example with the path (without a specified file) does somehow confuse... 
- Also explain that the report viewer is now deployed as part of jplag, so the offline use is not required if you don't develop with it

**Comment by nestabentum** [comment]
@sebinside 
> `ReportObjectFactory#createAndSaveReport` why the `#` for separating class and method?
It's JDoc syntax for referencing methods. Also, I think, IntelliJ used this syntax as well when copying references to methods.
> When explaining -r, the example with the path (without a specified file) does somehow confuse...
I'm not sure how to improve understandability here. Do you have a hint?

**Comment by sebinside** [comment]
@nestabentum ah, didn't know that with the `#`, then its fine. Regarding the clarification: Clearly specify if its a `path/to/folder` where a zip is saved or if its `path/to/file.zip` (or if its `path/to/folder` with `folder.zip`). That would resolve my issue

**Comment by tsaglam** [comment]
✅ Documentation incorporated into the wiki and the repo!
