### ISSUE TITLE
New branch strategy

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#635]
The `master` branch shall be renamed to `main` and contain the released version after the 4.0 release. The development version shall be on a separate branch called `dev` or `develop`.

## TODO
* Migrate all files [here](https://github.com/jplag/JPlag/search?q=master)

**Comment by dfuchss** [comment]
I would also opt for the git-flow workflow: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow or https://www.bluesource.at/blog/detail/git-flow
