### ISSUE TITLE
different language

### ISSUE THREAD

**Issue by umabalaji18** [jplag/jplag#64]
Is it possible to compare different languages ? In case if I want to check only the logic. May be this is not a issue just a question.
Example: If my directory contains both Java and c/c++ code, I want to know whether jplag compares two languages.
I could see that I can specify only one language and I should have only Java files in the directory in case I am checking Java files.
java -jar jplag-2.11.9-SNAPSHOT\jplag\target\jplag-0.0.3-SNAPSHOT.jar -l java17 -r results -s res1

**Comment by weigelt** [comment]
This is nothing we plan to implement in the near future, sorry.
However, even if we do, it won't be much help since code from different languages is often semantically different.
