### ISSUE TITLE
Clean-up public API to be consistent

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#648]
In preparation for the v4.0.0 release.

Random notes:

- [x] Clean up log (e.g. Stanford NLP)
- [x] Exception when using CLI with no args

**Comment by JanWittler** [comment]
https://github.com/jplag/JPlag/blob/ec2c3c47b3f1794ab9bcce132c556fb5f7f16e8d/jplag.frontend-utils/src/main/java/de/jplag/Language.java#L30-L36

Proposed change
```Java
     /** 
      * Parses a set of files in a directory. 
      * @param files are the files to parse. 
      * @return the list of parsed JPlag tokens. 
      */ 
     TokenList parse(File[] files); 
```

**Comment by dfuchss** [comment]
> https://github.com/jplag/JPlag/blob/ec2c3c47b3f1794ab9bcce132c556fb5f7f16e8d/jplag.frontend-utils/src/main/java/de/jplag/Language.java#L30-L36
> 
> Proposed change
> 
> ```java
>      /** 
>       * Parses a set of files in a directory. 
>       * @param files are the files to parse. 
>       * @return the list of parsed JPlag tokens. 
>       */ 
>      TokenList parse(File[] files); 
> ```

What about Collection<File> or List<File> ? Do we need the array here?

**Comment by JanWittler** [comment]
True, a collection (or Iterable) should probably suffice.
