### ISSUE TITLE
Error running version 3.0.0

### ISSUE THREAD

**Issue by cx-joaoguedes** [jplag/JPlag#689]
I'm running version 3.0.0 and I'm getting a NoClassDefFoundError: com/sun/source/tree/TreeVisitor
jplag never ran successfully on my machine

**Comment by tsaglam** [comment]
Did you download a released jar, or did you build the jar yourself? If you built it yourself, what mvn command did you use?
What maven and java version do you have installed?

**Comment by cx-joaoguedes** [comment]
@tsaglam thanks for the reply, I downloaded the released jar and ran "java -jar jplag.jar -l java ./submissions" given I wanted compare 2 files in the folder submissions

**Comment by tsaglam** [comment]
@cx-joaoguedes can you run `java -version` and tell me what the output is?

**Comment by cx-joaoguedes** [comment]
![image](https://user-images.githubusercontent.com/110476545/192232751-f1f5ef63-75d7-499c-86fe-c63ebdbed91b.png)

This is my java version

**Comment by tsaglam** [comment]
Hmm, that is odd indeed. You could try updating to the latest JDK, which would be 17.0.4, but that is just a guess. For me, it is working, I am on Win 10 and OpenJDK version "17.0.2" 2022-01-18.

**Comment by tsaglam** [comment]
> Thrown if the Java Virtual Machine or a ClassLoader instance tries to load in the definition of a class (as part of a normal method call or as part of creating a new instance using the new expression) and no definition of the class could be found.
> 
> The searched-for class definition existed when the currently executing class was compiled, but the definition can no longer be found.

[(source)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/NoClassDefFoundError.html)

I would try updating the JDK or installing a different variant of OpenJDK. It might be the case that a jar is missing from your JDK installation.

**Comment by cx-joaoguedes** [comment]
I tried java version jdk-19 and it finally worked. Thanks for all your help

**Comment by tsaglam** [comment]
@cx-joaoguedes I am glad it worked! We just released [v4.0.0](https://github.com/jplag/JPlag/releases/tag/v4.0.0), you can also use that version if you want!
