### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by tlsid** [jplag/jplag#69]
when I followed the README, tried to build jplag using mvn clean generate-sources package under the base directory, error occurred as following:
[INFO] Reactor Summary:
[INFO] 
[INFO] JPlag Plagiarism Detector 0.3-SNAPSHOT ............. SUCCESS [  0.114 s]
[INFO] frontend-utils 0.0.3-SNAPSHOT ...................... FAILURE [  0.285 s]
[INFO] chars 0.0.1-SNAPSHOT ............................... SKIPPED
[INFO] cpp 0.0.2-SNAPSHOT ................................. SKIPPED
[INFO] csharp-1.2 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] java-1.1exp 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] java-1.2 0.0.1-SNAPSHOT ............................ SKIPPED
[INFO] java-1.5 0.0.1-SNAPSHOT ............................ SKIPPED
[INFO] java-1.7 0.0.1-SNAPSHOT ............................ SKIPPED
[INFO] java-1.9 0.0.1-SNAPSHOT ............................ SKIPPED
[INFO] python-3 0.0.1-SNAPSHOT ............................ SKIPPED
[INFO] scheme 0.0.1-SNAPSHOT .............................. SKIPPED
[INFO] text 0.0.1-SNAPSHOT ................................ SKIPPED
[INFO] utils 0.0.3-SNAPSHOT ............................... SKIPPED
[INFO] jplag 2.12.1-SNAPSHOT .............................. SKIPPED
[INFO] JPlag Aggregator 0.0.1-SNAPSHOT .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.584 s
[INFO] Finished at: 2019-06-09T08:45:45-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project frontend-utils: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 11
[ERROR] Usage: javac <options> <source files>
[ERROR] use --help for a list of possible options
[ERROR] 
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :frontend-utils

**Comment by davidmitesh** [comment]
How this issue was solved? I am facing similar issue.Please help!

**Comment by AlexQueso** [comment]
I solved by changing manually the compiler in each pom.xml
Like this:

          <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

**Comment by davidmitesh** [comment]
@AlexQueso Do you mean to say I need to manually replace pom.xml of all the jplag.- folders in the jplag directory?

![image](https://user-images.githubusercontent.com/29304788/78766739-5faf9d80-79a9-11ea-8d51-3254c9bec913.png)

And one more question do I need to append the compiler code above in each pom.xml file or just replace the entire section of <build>.....</build>??

I am so confused. Please help!
