### ISSUE TITLE
Add documentation on how to select tokens

### ISSUE THREAD

**Issue by libre-man** [jplag/JPlag#70]
I'm trying to create a new frontend for JPLAG for Scala, however I'm having some trouble selecting the right set of tokens to use. It would be nice if there were some documentation on how to select an appropriate set of tokens. As too many would lead to false negatives, while too few would lead to false positives when matching.  How was this done for the other parsers, simply a gut feeling or something more advanced.

**Comment by Alberth289346** [comment]
Basically you want to preserve structure and not details. For example you could have a "value" token for any literal in an expression. One step higher, you could have an "expression" token for an entire expression.

I don't think there is a universal guide here. It also depends on the abstraction level of the language itself, for example. An imperative language may have much more detail in the expressions than a declarative language.

**Comment by tsaglam** [comment]
I just recently learned that the people over at @CodeGra-de have a few additional language frontends in [their fork](https://github.com/CodeGra-de/jplag) of JPlag. One of them seems to be a Scala frontend. Of course, this issue was opened quite some time ago, but if there is still a need for a Scala frontend maybe that helps.

@sebinside maybe we should talk to them in the near future regarding merging a few of their additional frontends back into JPlag.

**Comment by tsaglam** [comment]
Adding to this, as I recently thought about this a lot. Obviously, it depends on the language. For languages that are similar to Java/C++ (let's say the object-oriented languages), one can look at what tokens are transformed in the C++/Java frontends. There, around 60 token types are used, which can also act as a number to use as orientation. Next, you can always work test-driven here. Build a front-end and test it with two source codes (original and plagiarised). For other languages, it is not as easy. But there I would generally start with the more structural tokens (types, members, etc.) and continue with control flow (if, else, loops, switches, and similar). Also important are variable declarations, function calls, and comments.

Here are some hints from the JPlag literature:
> Prechelt et al. 2002:
> As a rule, tokens should be chosen such that they characterize the essence of a
> program’s structure (which is difficult to change by a plagiarist) rather than sur-
> face aspects. JPlag ignores whitespace, comments, and the names of identifiers.
> Moreover, JPlag puts semantic information into tokens where possible in order
> to reduce spurious substring matches that can occur by pure chance. For in-
> stance in Java, we use a Begin Method token instead of just an Open Brace
> token. Parser-based front ends are superior in this respect

> Prechelt et al. 2000:
> A parser front-end has the advantage of allowing for more semantic information to be represented in the token string.
> For instance in Java, we can create a BEGINMETHOD token instead of just a OPEN BRACE token.1
> As a rule, tokens should be chosen such that they characterize the essence of a program (which is difficult
> to change by a plagiarist) rather than surface aspects. For instance, whitespace and comments should never
> produce a token, since they are the most obvious points of attack. Some sorts of tokens may or may not
> be considered useful. For instance, the default token set for Java completely ignores expressions except for
> assignments and method calls; see the example in Table 3.1. The complete token lists are printed in Appendix B.
> The number of the line from which the token originates is stored within the token object so that it is possible
> to pinpoint any similarities between two files with respect to the original source files later. Note that internally
> each token is represented by a single character for the comparison.

**Comment by tsaglam** [comment]
We now provide extensive documentation on how to add new language modules in our wiki:
https://github.com/jplag/JPlag/wiki/4.-Adding-New-Languages

While more information might be added in the future, we consider this issue closed for now.
