### ISSUE TITLE
Documentation of the Java API in the README is wrong and difficult to understand

### ISSUE THREAD

**Issue by krusche** [jplag/JPlag#712]
I suggest updating the documentation, in particular showing how to transition from JPlag 3 to JPlag 4

**Comment by tsaglam** [comment]
Ah, good call, the example ist outdated. I will fix it. In the meantime, this is how it should be:

```java
Language language = new de.jplag.java.Language();
Set<File> submissionDirectories = Set.of(new File("path/to/rootDir"));
File baseCode = new File("path/to/baseCode");
JPlagOptions options = new JPlagOptions(language, submissionDirectories, Set.of()).withBaseCodeSubmissionDirectory(baseCode);

JPlag jplag = new JPlag(options);
JPlagResult result = jplag.run(); // Exception handling required here

// Optional
ReportObjectFactory reportObjectFactory = new ReportObjectFactory();
reportObjectFactory.createAndSaveReport(result, "/path/to/output");
```

**Comment by tsaglam** [comment]
> I suggest updating the documentation, in particular showing how to transition from JPlag 3 to JPlag 4

@krusche is the updated example listed above sufficient or do you think more information for migrating is required?

**Comment by krusche** [comment]
I think it's fine. Thanks for the quick fix
