### ISSUE TITLE
`Metric` data object stores UI description

### ISSUE THREAD

**Issue by JanWittler** [jplag/JPlag#717]
The [`Metric`](https://github.com/jplag/JPlag/blob/master/core/src/main/java/de/jplag/reporting/reportobject/model/Metric.java) record stores the description that should be shown in the report viewer. This breaks the intended separation between data and UI. As such, we should refactor `Metric` to only contain an identifier of the type of metric (e.g. modeled as an enum) and load the according description in the report viewer based on that identifier.

After this refactoring, we should move the [`Messages`](https://github.com/jplag/JPlag/blob/master/core/src/main/java/de/jplag/Messages.java) class and [all its resources](https://github.com/jplag/JPlag/tree/master/core/src/main/resources/de/jplag) to the CLI package and change the visibility to `protected`.

**Comment by tsaglam** [comment]
Closed by #1415.
