### ISSUE TITLE
What's the meaning of different colors in the detected code?

### ISSUE THREAD

**Issue by YiMingshan** [jplag/jplag#73]
After using JPlag to detect some programs, I thought the the different colors in the detected code stand the different degree of code similarity.  Is that rihgt? If it is right, please tell me the details. Thanks!

**Comment by salmanshokha** [comment]
Similar passages on both files are marked with the same color. But there can be large number of similar passages. So, I think different colors are used to represent the large many variety of passages, not the degree of code similarity. For instance, in one case I found that red and green are used to mark 10 and 18 similar tokens respectively whereas in another I discovered red and green are used to mark 10 and 8 tokens respectively.

Also, you may take a look at the help [file](jplag/src/main/resources/jplag/data/help-en.html) provided by JPlag.
