### ISSUE TITLE
Feature request: option for printing/(option for additional) printable view

### ISSUE THREAD

**Issue by chris21k** [jplag/JPlag#754]
Unfortunately, in our school we have to print out (pairs of) code submissions that are suspected of being plagiarism, annotate them accordingly (by hand) and send them to the examination board as a "proof" of plagarism. This is a legal thing. With "printing out", I also mean generating a pdf or similar. With JPlag 2.x it was perfectly possible to print each of the two html files (each with the whole code)  belonging to a single plagiarism pair.
So the feature request for the report viewer would be to add, for example, an additional view for that.  Maybe changing the main view accordingly would destroy online usability or clarity, but I am not sure about that. Clarity was imho also pretty good in JPlag 2.x .

Thanks for developing JPlag!

Chris

**Comment by tsaglam** [comment]
Closed by #1409. Will be released soon.

**Comment by chris21k** [comment]
Ah, many thanks, that helps a lot. You and JPlag are great!
