### ISSUE TITLE
Parse error on UTF-8 source

### ISSUE THREAD

**Issue by SindreSB** [jplag/jplag#77]
Hi, I'm using the C++ frontend on the latest snapchot. I can see there is an issue about failing to parse chinese sources (#7) which I guess might be related? I'm not using any chinese characters, but the submissions I'm checking contains nordic letters such as Æ, Ø and Å.

Do you know if this is this an issue of the frontend, of is there is an issue with the Jplag engine?

**Comment by SindreSB** [comment]
It appears my source might contain invalid utf-8, and so it's probably not a problem with the parser.

**Comment by spalt-alfred** [comment]
I would like to RE-OPEN this issue.
I also have parse errors when C#-Sources have german umlaute which are encoded as UTF8: äöü
