### ISSUE TITLE
Python3 front-end : 0 submission parsed successfully

### ISSUE THREAD

**Issue by fbolgar** [jplag/jplag#79]
Hello,

I am having issues using jplag with python3 front-end.

Indeed, i run jplag with the following command:

java -jar jplag.jar -r ~/result/ -l python3 -c solution.py solution.py

With solution.py:
```
#Exercice 1: Vitesse et amende
if ((vitesse_mesuree-5)-vitesse_autorisee>=20):
    amende=135
elif ((vitesse_mesuree-5)-vitesse_autorisee>=10) and ((vitesse_mesuree-5)-vitesse_autorisee<20):
    amende=90
elif ((vitesse_mesuree-5)-vitesse_autorisee<10) and ((vitesse_mesuree-5)-vitesse_autorisee>0):
    amende=68
else:
    amende=0`
```

But when I run the command I get the following output:

```
Language accepted: Python3 Parser
Command line: -r /home/ubuntu/result/ -l python3 -c solution.py solution.py 
initialize ok
0 submissions parsed successfully!
0 parser errors!
Error: Not enough valid submissions! (only 0 are valid):
```
Do you have any idea why parsing does not work ? Adding option -vd does not give any more information:

```
Language accepted: Python3 Parser
Command line: -vd -r /home/ubuntu/result/ -l python3 -c solution.py solution.py 
initialize ok
Files in submission 'solution.py':
  solution.py
Files in submission 'solution.py':
  solution.py
0 submissions parsed successfully!
0 parser errors!
Error: Not enough valid submissions! (only 0 are valid):
```

Best regards,

Florian Bolgar

**Comment by tsaglam** [comment]
`solution.py` seems to be incomplete, as the variables are not initialized. As the other commenter already stated, JPlag relies on syntactical correctness. If there are other issues with JPlag, feel free to let me know!
