### ISSUE TITLE
Document required JRE version

### ISSUE THREAD

**Issue by jtotht** [jplag/JPlag#840]
Based on #592, it seems like the JRE version required to _run_ JPlag is 17+. However, I didn’t find documentation about this either in the README or the wiki (the README documents that the Java source version JPlag can _analyze_ is 17, but this doesn’t necessarily need to match the JRE version, you could use non-JRE-provided tools to analyze files written in newer Java versions). Since users should install the JRE themselves, please document the JRE version they need to have.

**Comment by tsaglam** [comment]
The project readme contains a table with the languages version JPlag supports. You can find it [here](https://github.com/jplag/JPlag/blob/main/README.md#supported-languages).

**Comment by jtotht** [comment]
Thanks!
