### ISSUE TITLE
Option "-m <p>%" recognized as "-m <n>"

### ISSUE THREAD

**Issue by edetorres** [jplag/jplag#88]
Hello,
I'm trying to set the number of matches by % of similarity and after trying it many times I can't make it work.

I'm running:
_java -jar jplag-2.12.1-SNAPSHOT-jar-with-dependencies.jar -l c/c++ -s sources/ **-m 95%**_

But the console is showing:
_Language accepted: C/C++ Scanner [basic markup]
Command line: -l c/c++ -s sources/ -m 95
initialize ok_

So, it's not recognizing my 95 as a percentage but a number.

Anything I might be doing wrong?

**Comment by tsaglam** [comment]
On my first try, I could not reproduce that error, for me, it showed: `Command line: -l c/c++ -s C:\My\Path\test -m 95% `

Which OS and Terminal/Command Line application are you working with?

**Comment by edetorres** [comment]
Found the problem. Our mistake.
We were running the command from a Batch script and somehow we forgot to escape the % sign.

My bad... Sorry for the inconvenience.
